    bits 64
    
    pi2fw          mm0,mm7
    pi2fd          mm0,mm7
    pf2iw          mm0,mm7
    pf2id          mm0,mm7
    pfrsqrtv       mm0,mm7
    pfnacc         mm0,mm7
    pfpnacc        mm0,mm7
    pfcmpge        mm0,mm7
    pfmin          mm0,mm7
    pfmin          mm0,mm7
    pfrsqrt        mm0,mm7
    pfsub          mm0,mm7
    pfadd          mm0,mm7
    pfcmpgt        mm0,mm7
    pfmax          mm0,mm7
    pfrcpit1       mm0,mm7
    pfrsqit1       mm0,mm7
    pfsubr         mm0,mm7
    pfacc          mm0,mm7
    pfcmpeq        mm0,mm7
    pfmul          mm0,mm7
    pfrcpit2       mm0,mm7
    pswapd         mm0,mm7
    pavgusb        mm0,mm7
    
    pi2fw          mm0,[rbx]
    pi2fd          mm0,[rbx]
    pf2iw          mm0,[rbx]
    pf2id          mm0,[rbx]
    pfrsqrtv       mm0,[rbx]
    pfnacc         mm0,[rbx]
    pfpnacc        mm0,[rbx]
    pfcmpge        mm0,[rbx]
    pfmin          mm0,[rbx]
    pfmin          mm0,[rbx]
    pfrsqrt        mm0,[rbx]
    pfsub          mm0,[rbx]
    pfadd          mm0,[rbx]
    pfcmpgt        mm0,[rbx]
    pfmax          mm0,[rbx]
    pfrcpit1       mm0,[rbx]
    pfrsqit1       mm0,[rbx]
    pfsubr         mm0,[rbx]
    pfacc          mm0,[rbx]
    pfcmpeq        mm0,[rbx]
    pfmul          mm0,[rbx]
    pfrcpit2       mm0,[rbx]
    pswapd         mm0,[rbx]
    pavgusb        mm0,[rbx]