    bits 64

    cvttps2pi      mm0,xmm7  
    cvttpd2pi      mm0,xmm7  
    cvtps2pi       mm0,xmm7    
    cvtpd2pi       mm0,xmm7   
    punpcklbw      mm0,mm7   
    punpcklwd      mm0,mm7    
    punpckldq      mm0,mm7    
    packsswb       mm0,mm7    
    pcmpgtb        mm0,mm7    
    pcmpgtw        mm0,mm7    
    pcmpgtd        mm0,mm7    
    packuswb       mm0,mm7    
    punpckhbw      mm0,mm7    
    punpckhwd      mm0,mm7    
    punpckhdq      mm0,mm7    
    packssdw       mm0,mm7    
    movd           mm0,edx    
    movq           mm0,rdx
    movq           mm0,mm7    
    pshufw         mm0,mm7,10 
    pcmpeqb        mm0,mm7    
    pcmpeqw        mm0,mm7    
    pcmpeqd        mm0,mm7    
    movq           rdx,mm0    
    movq           mm7,mm0    
    pinsrw         mm0,esi,10 
    pinsrw         mm0,[rbx],10 
    psrlw          mm0,mm7    
    psrld          mm0,mm7    
    psrlq          mm0,mm7    
    paddq          mm0,mm7    
    pmullw         mm0,mm7    
    movdq2q        mm0,xmm7
    psubusb        mm0,mm7    
    psubusw        mm0,mm7    
    pminub         mm0,mm7    
    pand           mm0,mm7    
    paddusb        mm0,mm7    
    paddusw        mm0,mm7    
    pmaxub         mm0,mm7    
    pandn          mm0,mm7    
    pavgb          mm0,mm7    
    psraw          mm0,mm7    
    psrad          mm0,mm7    
    pavgw          mm0,mm7    
    pmulhuw        mm0,mm7    
    pmulhw         mm0,mm7    
    movntq         [rbx],mm0    
    psubsb         mm0,mm7    
    psubsw         mm0,mm7    
    pminsw         mm0,mm7    
    por            mm0,mm7    
    paddsb         mm0,mm7    
    paddsw         mm0,mm7    
    pmaxsw         mm0,mm7    
    pxor           mm0,mm7    
    psllw          mm0,mm7    
    pslld          mm0,mm7    
    psllq          mm0,mm7    
    pmuludq        mm0,mm7    
    pmaddwd        mm0,mm7    
    psadbw         mm0,mm7    
    maskmovq       mm0,mm7    
    psubb          mm0,mm7    
    psubw          mm0,mm7    
    psubd          mm0,mm7    
    psubq          mm0,mm7    
    paddb          mm0,mm7    
    paddw          mm0,mm7    
    paddd          mm0,mm7    
    
    cvttps2pi      mm0,xmm15    
    cvttpd2pi      mm0,xmm15   
    cvtps2pi       mm0,xmm15    
    cvtpd2pi       mm0,xmm15   
    punpcklbw      mm0,[rbx]    
    punpcklwd      mm0,[rbx]    
    punpckldq      mm0,[rbx]    
    packsswb       mm0,[rbx]    
    pcmpgtb        mm0,[rbx]    
    pcmpgtw        mm0,[rbx]    
    pcmpgtd        mm0,[rbx]    
    packuswb       mm0,[rbx]    
    punpckhbw      mm0,[rbx]    
    punpckhwd      mm0,[rbx]    
    punpckhdq      mm0,[rbx]    
    packssdw       mm0,[rbx]    
    movd           mm0,[rbx]    
    movq           mm0,[rbx] 
    movq           mm0,[rbx]    
    pshufw         mm0,[rbx],10
    pcmpeqb        mm0,[rbx]    
    pcmpeqw        mm0,[rbx]    
    pcmpeqd        mm0,[rbx]    
    movq           [rbx],mm0    
    movq           [rbx],mm0    
    pinsrw         mm0,r15d,10
    pinsrw         mm0,[rbx],10
    psrlw          mm0,[rbx]    
    psrld          mm0,[rbx]    
    psrlq          mm0,[rbx]    
    paddq          mm0,[rbx]    
    pmullw         mm0,[rbx]    
    movdq2q        mm0,xmm15
    psubusb        mm0,[rbx]    
    psubusw        mm0,[rbx]    
    pminub         mm0,[rbx]    
    pand           mm0,[rbx]    
    paddusb        mm0,[rbx]    
    paddusw        mm0,[rbx]    
    pmaxub         mm0,[rbx]    
    pandn          mm0,[rbx]    
    pavgb          mm0,[rbx]    
    psraw          mm0,[rbx]    
    psrad          mm0,[rbx]    
    pavgw          mm0,[rbx]    
    pmulhuw        mm0,[rbx]    
    pmulhw         mm0,[rbx]    
    movntq         [rbx],mm0    
    psubsb         mm0,[rbx]    
    psubsw         mm0,[rbx]    
    pminsw         mm0,[rbx]    
    por            mm0,[rbx]    
    paddsb         mm0,[rbx]    
    paddsw         mm0,[rbx]    
    pmaxsw         mm0,[rbx]    
    pxor           mm0,[rbx]    
    psllw          mm0,[rbx]    
    pslld          mm0,[rbx]    
    psllq          mm0,[rbx]    
    pmuludq        mm0,[rbx]    
    pmaddwd        mm0,[rbx]    
    psadbw         mm0,[rbx]    
    maskmovq       mm0,mm7
    psubb          mm0,[rbx]    
    psubw          mm0,[rbx]    
    psubd          mm0,[rbx]    
    psubq          mm0,[rbx]    
    paddb          mm0,[rbx]    
    paddw          mm0,[rbx]    
    paddd          mm0,[rbx]    

    pshufb         mm3,mm4
    phaddw         mm3,mm4
    phaddd         mm3,mm4
    phaddsw        mm3,mm4
    pmaddubsw      mm3,mm4
    phsubw         mm3,mm4
    phsubd         mm3,mm4
    phsubsw        mm3,mm4
    psignb         mm3,mm4
    psignw         mm3,mm4
    psignd         mm3,mm4
    pmulhrsw       mm3,mm4
    pabsb          mm3,mm4
    pabsw          mm3,mm4
    pabsd          mm3,mm4

    pshufb         mm7,[rbx]
    phaddw         mm7,[rbx]
    phaddd         mm7,[rbx]
    phaddsw        mm7,[rbx]
    pmaddubsw      mm7,[rbx]
    phsubw         mm7,[rbx]
    phsubd         mm7,[rbx]
    phsubsw        mm7,[rbx]
    psignb         mm7,[rbx]
    psignw         mm7,[rbx]
    psignd         mm7,[rbx]
    pmulhrsw       mm7,[rbx]
    pabsb          mm7,[rbx]
    pabsw          mm7,[rbx]
    pabsd          mm7,[rbx]

    palignr        mm1,mm2,10
    palignr        mm1,[rbx],10