/*
 * Copyright (c) 2025 Bitdefender
 * SPDX-License-Identifier: Apache-2.0
 */

//
// This file was auto-generated by generate_tables.py. DO NOT MODIFY!
//

#ifndef BDX86_TABLE_XOP_H
#define BDX86_TABLE_XOP_H

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_0a_opcode_12_modrmreg_01_leaf = 
{
    ND_ILUT_INSTRUCTION,
    1336, // LWPVAL By,Ed,Id
    0,
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_0a_opcode_12_modrmreg_00_leaf = 
{
    ND_ILUT_INSTRUCTION,
    1335, // LWPINS By,Ed,Id
    0,
};

const ND_TABLE_MODRM_REG gXopMap_mmmmm_0a_opcode_12_modrmreg = 
{
    ND_ILUT_MODRM_REG,
    0,
    {
        /* 00 */ (const void *)&gXopMap_mmmmm_0a_opcode_12_modrmreg_00_leaf,
        /* 01 */ (const void *)&gXopMap_mmmmm_0a_opcode_12_modrmreg_01_leaf,
        /* 02 */ (const void *)ND_NULL,
        /* 03 */ (const void *)ND_NULL,
        /* 04 */ (const void *)ND_NULL,
        /* 05 */ (const void *)ND_NULL,
        /* 06 */ (const void *)ND_NULL,
        /* 07 */ (const void *)ND_NULL,
    }
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_0a_opcode_10_nov_00_leaf = 
{
    ND_ILUT_INSTRUCTION,
    188, // BEXTR Gy,Ey,Id
    0,
};

const ND_TABLE_FILTER gXopMap_mmmmm_0a_opcode_10_nov = 
{
    ND_ILUT_FLT_NOV,
    0,
    {
        /* 00 */ (const void *)&gXopMap_mmmmm_0a_opcode_10_nov_00_leaf,
    }
};

const ND_TABLE_OPCODE gXopMap_mmmmm_0a_opcode = 
{
    ND_ILUT_OPCODE,
    0,
    {
        /* 00 */ (const void *)ND_NULL,
        /* 01 */ (const void *)ND_NULL,
        /* 02 */ (const void *)ND_NULL,
        /* 03 */ (const void *)ND_NULL,
        /* 04 */ (const void *)ND_NULL,
        /* 05 */ (const void *)ND_NULL,
        /* 06 */ (const void *)ND_NULL,
        /* 07 */ (const void *)ND_NULL,
        /* 08 */ (const void *)ND_NULL,
        /* 09 */ (const void *)ND_NULL,
        /* 0a */ (const void *)ND_NULL,
        /* 0b */ (const void *)ND_NULL,
        /* 0c */ (const void *)ND_NULL,
        /* 0d */ (const void *)ND_NULL,
        /* 0e */ (const void *)ND_NULL,
        /* 0f */ (const void *)ND_NULL,
        /* 10 */ (const void *)&gXopMap_mmmmm_0a_opcode_10_nov,
        /* 11 */ (const void *)ND_NULL,
        /* 12 */ (const void *)&gXopMap_mmmmm_0a_opcode_12_modrmreg,
        /* 13 */ (const void *)ND_NULL,
        /* 14 */ (const void *)ND_NULL,
        /* 15 */ (const void *)ND_NULL,
        /* 16 */ (const void *)ND_NULL,
        /* 17 */ (const void *)ND_NULL,
        /* 18 */ (const void *)ND_NULL,
        /* 19 */ (const void *)ND_NULL,
        /* 1a */ (const void *)ND_NULL,
        /* 1b */ (const void *)ND_NULL,
        /* 1c */ (const void *)ND_NULL,
        /* 1d */ (const void *)ND_NULL,
        /* 1e */ (const void *)ND_NULL,
        /* 1f */ (const void *)ND_NULL,
        /* 20 */ (const void *)ND_NULL,
        /* 21 */ (const void *)ND_NULL,
        /* 22 */ (const void *)ND_NULL,
        /* 23 */ (const void *)ND_NULL,
        /* 24 */ (const void *)ND_NULL,
        /* 25 */ (const void *)ND_NULL,
        /* 26 */ (const void *)ND_NULL,
        /* 27 */ (const void *)ND_NULL,
        /* 28 */ (const void *)ND_NULL,
        /* 29 */ (const void *)ND_NULL,
        /* 2a */ (const void *)ND_NULL,
        /* 2b */ (const void *)ND_NULL,
        /* 2c */ (const void *)ND_NULL,
        /* 2d */ (const void *)ND_NULL,
        /* 2e */ (const void *)ND_NULL,
        /* 2f */ (const void *)ND_NULL,
        /* 30 */ (const void *)ND_NULL,
        /* 31 */ (const void *)ND_NULL,
        /* 32 */ (const void *)ND_NULL,
        /* 33 */ (const void *)ND_NULL,
        /* 34 */ (const void *)ND_NULL,
        /* 35 */ (const void *)ND_NULL,
        /* 36 */ (const void *)ND_NULL,
        /* 37 */ (const void *)ND_NULL,
        /* 38 */ (const void *)ND_NULL,
        /* 39 */ (const void *)ND_NULL,
        /* 3a */ (const void *)ND_NULL,
        /* 3b */ (const void *)ND_NULL,
        /* 3c */ (const void *)ND_NULL,
        /* 3d */ (const void *)ND_NULL,
        /* 3e */ (const void *)ND_NULL,
        /* 3f */ (const void *)ND_NULL,
        /* 40 */ (const void *)ND_NULL,
        /* 41 */ (const void *)ND_NULL,
        /* 42 */ (const void *)ND_NULL,
        /* 43 */ (const void *)ND_NULL,
        /* 44 */ (const void *)ND_NULL,
        /* 45 */ (const void *)ND_NULL,
        /* 46 */ (const void *)ND_NULL,
        /* 47 */ (const void *)ND_NULL,
        /* 48 */ (const void *)ND_NULL,
        /* 49 */ (const void *)ND_NULL,
        /* 4a */ (const void *)ND_NULL,
        /* 4b */ (const void *)ND_NULL,
        /* 4c */ (const void *)ND_NULL,
        /* 4d */ (const void *)ND_NULL,
        /* 4e */ (const void *)ND_NULL,
        /* 4f */ (const void *)ND_NULL,
        /* 50 */ (const void *)ND_NULL,
        /* 51 */ (const void *)ND_NULL,
        /* 52 */ (const void *)ND_NULL,
        /* 53 */ (const void *)ND_NULL,
        /* 54 */ (const void *)ND_NULL,
        /* 55 */ (const void *)ND_NULL,
        /* 56 */ (const void *)ND_NULL,
        /* 57 */ (const void *)ND_NULL,
        /* 58 */ (const void *)ND_NULL,
        /* 59 */ (const void *)ND_NULL,
        /* 5a */ (const void *)ND_NULL,
        /* 5b */ (const void *)ND_NULL,
        /* 5c */ (const void *)ND_NULL,
        /* 5d */ (const void *)ND_NULL,
        /* 5e */ (const void *)ND_NULL,
        /* 5f */ (const void *)ND_NULL,
        /* 60 */ (const void *)ND_NULL,
        /* 61 */ (const void *)ND_NULL,
        /* 62 */ (const void *)ND_NULL,
        /* 63 */ (const void *)ND_NULL,
        /* 64 */ (const void *)ND_NULL,
        /* 65 */ (const void *)ND_NULL,
        /* 66 */ (const void *)ND_NULL,
        /* 67 */ (const void *)ND_NULL,
        /* 68 */ (const void *)ND_NULL,
        /* 69 */ (const void *)ND_NULL,
        /* 6a */ (const void *)ND_NULL,
        /* 6b */ (const void *)ND_NULL,
        /* 6c */ (const void *)ND_NULL,
        /* 6d */ (const void *)ND_NULL,
        /* 6e */ (const void *)ND_NULL,
        /* 6f */ (const void *)ND_NULL,
        /* 70 */ (const void *)ND_NULL,
        /* 71 */ (const void *)ND_NULL,
        /* 72 */ (const void *)ND_NULL,
        /* 73 */ (const void *)ND_NULL,
        /* 74 */ (const void *)ND_NULL,
        /* 75 */ (const void *)ND_NULL,
        /* 76 */ (const void *)ND_NULL,
        /* 77 */ (const void *)ND_NULL,
        /* 78 */ (const void *)ND_NULL,
        /* 79 */ (const void *)ND_NULL,
        /* 7a */ (const void *)ND_NULL,
        /* 7b */ (const void *)ND_NULL,
        /* 7c */ (const void *)ND_NULL,
        /* 7d */ (const void *)ND_NULL,
        /* 7e */ (const void *)ND_NULL,
        /* 7f */ (const void *)ND_NULL,
        /* 80 */ (const void *)ND_NULL,
        /* 81 */ (const void *)ND_NULL,
        /* 82 */ (const void *)ND_NULL,
        /* 83 */ (const void *)ND_NULL,
        /* 84 */ (const void *)ND_NULL,
        /* 85 */ (const void *)ND_NULL,
        /* 86 */ (const void *)ND_NULL,
        /* 87 */ (const void *)ND_NULL,
        /* 88 */ (const void *)ND_NULL,
        /* 89 */ (const void *)ND_NULL,
        /* 8a */ (const void *)ND_NULL,
        /* 8b */ (const void *)ND_NULL,
        /* 8c */ (const void *)ND_NULL,
        /* 8d */ (const void *)ND_NULL,
        /* 8e */ (const void *)ND_NULL,
        /* 8f */ (const void *)ND_NULL,
        /* 90 */ (const void *)ND_NULL,
        /* 91 */ (const void *)ND_NULL,
        /* 92 */ (const void *)ND_NULL,
        /* 93 */ (const void *)ND_NULL,
        /* 94 */ (const void *)ND_NULL,
        /* 95 */ (const void *)ND_NULL,
        /* 96 */ (const void *)ND_NULL,
        /* 97 */ (const void *)ND_NULL,
        /* 98 */ (const void *)ND_NULL,
        /* 99 */ (const void *)ND_NULL,
        /* 9a */ (const void *)ND_NULL,
        /* 9b */ (const void *)ND_NULL,
        /* 9c */ (const void *)ND_NULL,
        /* 9d */ (const void *)ND_NULL,
        /* 9e */ (const void *)ND_NULL,
        /* 9f */ (const void *)ND_NULL,
        /* a0 */ (const void *)ND_NULL,
        /* a1 */ (const void *)ND_NULL,
        /* a2 */ (const void *)ND_NULL,
        /* a3 */ (const void *)ND_NULL,
        /* a4 */ (const void *)ND_NULL,
        /* a5 */ (const void *)ND_NULL,
        /* a6 */ (const void *)ND_NULL,
        /* a7 */ (const void *)ND_NULL,
        /* a8 */ (const void *)ND_NULL,
        /* a9 */ (const void *)ND_NULL,
        /* aa */ (const void *)ND_NULL,
        /* ab */ (const void *)ND_NULL,
        /* ac */ (const void *)ND_NULL,
        /* ad */ (const void *)ND_NULL,
        /* ae */ (const void *)ND_NULL,
        /* af */ (const void *)ND_NULL,
        /* b0 */ (const void *)ND_NULL,
        /* b1 */ (const void *)ND_NULL,
        /* b2 */ (const void *)ND_NULL,
        /* b3 */ (const void *)ND_NULL,
        /* b4 */ (const void *)ND_NULL,
        /* b5 */ (const void *)ND_NULL,
        /* b6 */ (const void *)ND_NULL,
        /* b7 */ (const void *)ND_NULL,
        /* b8 */ (const void *)ND_NULL,
        /* b9 */ (const void *)ND_NULL,
        /* ba */ (const void *)ND_NULL,
        /* bb */ (const void *)ND_NULL,
        /* bc */ (const void *)ND_NULL,
        /* bd */ (const void *)ND_NULL,
        /* be */ (const void *)ND_NULL,
        /* bf */ (const void *)ND_NULL,
        /* c0 */ (const void *)ND_NULL,
        /* c1 */ (const void *)ND_NULL,
        /* c2 */ (const void *)ND_NULL,
        /* c3 */ (const void *)ND_NULL,
        /* c4 */ (const void *)ND_NULL,
        /* c5 */ (const void *)ND_NULL,
        /* c6 */ (const void *)ND_NULL,
        /* c7 */ (const void *)ND_NULL,
        /* c8 */ (const void *)ND_NULL,
        /* c9 */ (const void *)ND_NULL,
        /* ca */ (const void *)ND_NULL,
        /* cb */ (const void *)ND_NULL,
        /* cc */ (const void *)ND_NULL,
        /* cd */ (const void *)ND_NULL,
        /* ce */ (const void *)ND_NULL,
        /* cf */ (const void *)ND_NULL,
        /* d0 */ (const void *)ND_NULL,
        /* d1 */ (const void *)ND_NULL,
        /* d2 */ (const void *)ND_NULL,
        /* d3 */ (const void *)ND_NULL,
        /* d4 */ (const void *)ND_NULL,
        /* d5 */ (const void *)ND_NULL,
        /* d6 */ (const void *)ND_NULL,
        /* d7 */ (const void *)ND_NULL,
        /* d8 */ (const void *)ND_NULL,
        /* d9 */ (const void *)ND_NULL,
        /* da */ (const void *)ND_NULL,
        /* db */ (const void *)ND_NULL,
        /* dc */ (const void *)ND_NULL,
        /* dd */ (const void *)ND_NULL,
        /* de */ (const void *)ND_NULL,
        /* df */ (const void *)ND_NULL,
        /* e0 */ (const void *)ND_NULL,
        /* e1 */ (const void *)ND_NULL,
        /* e2 */ (const void *)ND_NULL,
        /* e3 */ (const void *)ND_NULL,
        /* e4 */ (const void *)ND_NULL,
        /* e5 */ (const void *)ND_NULL,
        /* e6 */ (const void *)ND_NULL,
        /* e7 */ (const void *)ND_NULL,
        /* e8 */ (const void *)ND_NULL,
        /* e9 */ (const void *)ND_NULL,
        /* ea */ (const void *)ND_NULL,
        /* eb */ (const void *)ND_NULL,
        /* ec */ (const void *)ND_NULL,
        /* ed */ (const void *)ND_NULL,
        /* ee */ (const void *)ND_NULL,
        /* ef */ (const void *)ND_NULL,
        /* f0 */ (const void *)ND_NULL,
        /* f1 */ (const void *)ND_NULL,
        /* f2 */ (const void *)ND_NULL,
        /* f3 */ (const void *)ND_NULL,
        /* f4 */ (const void *)ND_NULL,
        /* f5 */ (const void *)ND_NULL,
        /* f6 */ (const void *)ND_NULL,
        /* f7 */ (const void *)ND_NULL,
        /* f8 */ (const void *)ND_NULL,
        /* f9 */ (const void *)ND_NULL,
        /* fa */ (const void *)ND_NULL,
        /* fb */ (const void *)ND_NULL,
        /* fc */ (const void *)ND_NULL,
        /* fd */ (const void *)ND_NULL,
        /* fe */ (const void *)ND_NULL,
        /* ff */ (const void *)ND_NULL,
    }
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_09_opcode_e3_nov_00_leaf = 
{
    ND_ILUT_INSTRUCTION,
    3673, // VPHSUBDQ Vdq,Wdq
    0,
};

const ND_TABLE_FILTER gXopMap_mmmmm_09_opcode_e3_nov = 
{
    ND_ILUT_FLT_NOV,
    0,
    {
        /* 00 */ (const void *)&gXopMap_mmmmm_09_opcode_e3_nov_00_leaf,
    }
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_09_opcode_e2_nov_00_leaf = 
{
    ND_ILUT_INSTRUCTION,
    3676, // VPHSUBWD Vdq,Wdq
    0,
};

const ND_TABLE_FILTER gXopMap_mmmmm_09_opcode_e2_nov = 
{
    ND_ILUT_FLT_NOV,
    0,
    {
        /* 00 */ (const void *)&gXopMap_mmmmm_09_opcode_e2_nov_00_leaf,
    }
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_09_opcode_e1_nov_00_leaf = 
{
    ND_ILUT_INSTRUCTION,
    3671, // VPHSUBBW Vdq,Wdq
    0,
};

const ND_TABLE_FILTER gXopMap_mmmmm_09_opcode_e1_nov = 
{
    ND_ILUT_FLT_NOV,
    0,
    {
        /* 00 */ (const void *)&gXopMap_mmmmm_09_opcode_e1_nov_00_leaf,
    }
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_09_opcode_db_nov_00_leaf = 
{
    ND_ILUT_INSTRUCTION,
    3664, // VPHADDUDQ Vdq,Wdq
    0,
};

const ND_TABLE_FILTER gXopMap_mmmmm_09_opcode_db_nov = 
{
    ND_ILUT_FLT_NOV,
    0,
    {
        /* 00 */ (const void *)&gXopMap_mmmmm_09_opcode_db_nov_00_leaf,
    }
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_09_opcode_d7_nov_00_leaf = 
{
    ND_ILUT_INSTRUCTION,
    3666, // VPHADDUWQ Vdq,Wdq
    0,
};

const ND_TABLE_FILTER gXopMap_mmmmm_09_opcode_d7_nov = 
{
    ND_ILUT_FLT_NOV,
    0,
    {
        /* 00 */ (const void *)&gXopMap_mmmmm_09_opcode_d7_nov_00_leaf,
    }
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_09_opcode_d6_nov_00_leaf = 
{
    ND_ILUT_INSTRUCTION,
    3665, // VPHADDUWD Vdq,Wdq
    0,
};

const ND_TABLE_FILTER gXopMap_mmmmm_09_opcode_d6_nov = 
{
    ND_ILUT_FLT_NOV,
    0,
    {
        /* 00 */ (const void *)&gXopMap_mmmmm_09_opcode_d6_nov_00_leaf,
    }
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_09_opcode_d3_nov_00_leaf = 
{
    ND_ILUT_INSTRUCTION,
    3662, // VPHADDUBQ Vdq,Wdq
    0,
};

const ND_TABLE_FILTER gXopMap_mmmmm_09_opcode_d3_nov = 
{
    ND_ILUT_FLT_NOV,
    0,
    {
        /* 00 */ (const void *)&gXopMap_mmmmm_09_opcode_d3_nov_00_leaf,
    }
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_09_opcode_d2_nov_00_leaf = 
{
    ND_ILUT_INSTRUCTION,
    3661, // VPHADDUBD Vdq,Wdq
    0,
};

const ND_TABLE_FILTER gXopMap_mmmmm_09_opcode_d2_nov = 
{
    ND_ILUT_FLT_NOV,
    0,
    {
        /* 00 */ (const void *)&gXopMap_mmmmm_09_opcode_d2_nov_00_leaf,
    }
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_09_opcode_d1_nov_00_leaf = 
{
    ND_ILUT_INSTRUCTION,
    3663, // VPHADDUBW Vdq,Wdq
    0,
};

const ND_TABLE_FILTER gXopMap_mmmmm_09_opcode_d1_nov = 
{
    ND_ILUT_FLT_NOV,
    0,
    {
        /* 00 */ (const void *)&gXopMap_mmmmm_09_opcode_d1_nov_00_leaf,
    }
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_09_opcode_cb_nov_00_leaf = 
{
    ND_ILUT_INSTRUCTION,
    3659, // VPHADDDQ Vdq,Wdq
    0,
};

const ND_TABLE_FILTER gXopMap_mmmmm_09_opcode_cb_nov = 
{
    ND_ILUT_FLT_NOV,
    0,
    {
        /* 00 */ (const void *)&gXopMap_mmmmm_09_opcode_cb_nov_00_leaf,
    }
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_09_opcode_c7_nov_00_leaf = 
{
    ND_ILUT_INSTRUCTION,
    3669, // VPHADDWQ Vdq,Wdq
    0,
};

const ND_TABLE_FILTER gXopMap_mmmmm_09_opcode_c7_nov = 
{
    ND_ILUT_FLT_NOV,
    0,
    {
        /* 00 */ (const void *)&gXopMap_mmmmm_09_opcode_c7_nov_00_leaf,
    }
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_09_opcode_c6_nov_00_leaf = 
{
    ND_ILUT_INSTRUCTION,
    3668, // VPHADDWD Vdq,Wdq
    0,
};

const ND_TABLE_FILTER gXopMap_mmmmm_09_opcode_c6_nov = 
{
    ND_ILUT_FLT_NOV,
    0,
    {
        /* 00 */ (const void *)&gXopMap_mmmmm_09_opcode_c6_nov_00_leaf,
    }
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_09_opcode_c3_nov_00_leaf = 
{
    ND_ILUT_INSTRUCTION,
    3656, // VPHADDBQ Vdq,Wdq
    0,
};

const ND_TABLE_FILTER gXopMap_mmmmm_09_opcode_c3_nov = 
{
    ND_ILUT_FLT_NOV,
    0,
    {
        /* 00 */ (const void *)&gXopMap_mmmmm_09_opcode_c3_nov_00_leaf,
    }
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_09_opcode_c2_nov_00_leaf = 
{
    ND_ILUT_INSTRUCTION,
    3655, // VPHADDBD Vdq,Wdq
    0,
};

const ND_TABLE_FILTER gXopMap_mmmmm_09_opcode_c2_nov = 
{
    ND_ILUT_FLT_NOV,
    0,
    {
        /* 00 */ (const void *)&gXopMap_mmmmm_09_opcode_c2_nov_00_leaf,
    }
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_09_opcode_c1_nov_00_leaf = 
{
    ND_ILUT_INSTRUCTION,
    3657, // VPHADDBW Vdq,Wdq
    0,
};

const ND_TABLE_FILTER gXopMap_mmmmm_09_opcode_c1_nov = 
{
    ND_ILUT_FLT_NOV,
    0,
    {
        /* 00 */ (const void *)&gXopMap_mmmmm_09_opcode_c1_nov_00_leaf,
    }
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_09_opcode_9b_w_01_leaf = 
{
    ND_ILUT_INSTRUCTION,
    3862, // VPSHAQ Vdq,Hdq,Wdq
    0,
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_09_opcode_9b_w_00_leaf = 
{
    ND_ILUT_INSTRUCTION,
    3861, // VPSHAQ Vdq,Wdq,Hdq
    0,
};

const ND_TABLE_EX_W gXopMap_mmmmm_09_opcode_9b_w = 
{
    ND_ILUT_EX_W,
    0,
    {
        /* 00 */ (const void *)&gXopMap_mmmmm_09_opcode_9b_w_00_leaf,
        /* 01 */ (const void *)&gXopMap_mmmmm_09_opcode_9b_w_01_leaf,
    }
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_09_opcode_9a_w_01_leaf = 
{
    ND_ILUT_INSTRUCTION,
    3860, // VPSHAD Vdq,Hdq,Wdq
    0,
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_09_opcode_9a_w_00_leaf = 
{
    ND_ILUT_INSTRUCTION,
    3859, // VPSHAD Vdq,Wdq,Hdq
    0,
};

const ND_TABLE_EX_W gXopMap_mmmmm_09_opcode_9a_w = 
{
    ND_ILUT_EX_W,
    0,
    {
        /* 00 */ (const void *)&gXopMap_mmmmm_09_opcode_9a_w_00_leaf,
        /* 01 */ (const void *)&gXopMap_mmmmm_09_opcode_9a_w_01_leaf,
    }
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_09_opcode_99_w_01_leaf = 
{
    ND_ILUT_INSTRUCTION,
    3864, // VPSHAW Vdq,Hdq,Wdq
    0,
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_09_opcode_99_w_00_leaf = 
{
    ND_ILUT_INSTRUCTION,
    3863, // VPSHAW Vdq,Wdq,Hdq
    0,
};

const ND_TABLE_EX_W gXopMap_mmmmm_09_opcode_99_w = 
{
    ND_ILUT_EX_W,
    0,
    {
        /* 00 */ (const void *)&gXopMap_mmmmm_09_opcode_99_w_00_leaf,
        /* 01 */ (const void *)&gXopMap_mmmmm_09_opcode_99_w_01_leaf,
    }
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_09_opcode_98_w_01_leaf = 
{
    ND_ILUT_INSTRUCTION,
    3858, // VPSHAB Vdq,Hdq,Wdq
    0,
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_09_opcode_98_w_00_leaf = 
{
    ND_ILUT_INSTRUCTION,
    3857, // VPSHAB Vdq,Wdq,Hdq
    0,
};

const ND_TABLE_EX_W gXopMap_mmmmm_09_opcode_98_w = 
{
    ND_ILUT_EX_W,
    0,
    {
        /* 00 */ (const void *)&gXopMap_mmmmm_09_opcode_98_w_00_leaf,
        /* 01 */ (const void *)&gXopMap_mmmmm_09_opcode_98_w_01_leaf,
    }
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_09_opcode_97_w_01_leaf = 
{
    ND_ILUT_INSTRUCTION,
    3877, // VPSHLQ Vdq,Hdq,Wdq
    0,
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_09_opcode_97_w_00_leaf = 
{
    ND_ILUT_INSTRUCTION,
    3876, // VPSHLQ Vdq,Wdq,Hdq
    0,
};

const ND_TABLE_EX_W gXopMap_mmmmm_09_opcode_97_w = 
{
    ND_ILUT_EX_W,
    0,
    {
        /* 00 */ (const void *)&gXopMap_mmmmm_09_opcode_97_w_00_leaf,
        /* 01 */ (const void *)&gXopMap_mmmmm_09_opcode_97_w_01_leaf,
    }
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_09_opcode_96_w_01_leaf = 
{
    ND_ILUT_INSTRUCTION,
    3868, // VPSHLB Vdq,Hdq,Wdq
    0,
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_09_opcode_96_w_00_leaf = 
{
    ND_ILUT_INSTRUCTION,
    3869, // VPSHLD Vdq,Wdq,Hdq
    0,
};

const ND_TABLE_EX_W gXopMap_mmmmm_09_opcode_96_w = 
{
    ND_ILUT_EX_W,
    0,
    {
        /* 00 */ (const void *)&gXopMap_mmmmm_09_opcode_96_w_00_leaf,
        /* 01 */ (const void *)&gXopMap_mmmmm_09_opcode_96_w_01_leaf,
    }
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_09_opcode_95_w_01_leaf = 
{
    ND_ILUT_INSTRUCTION,
    3867, // VPSHLB Vdq,Hdq,Wdq
    0,
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_09_opcode_95_w_00_leaf = 
{
    ND_ILUT_INSTRUCTION,
    3878, // VPSHLW Vdq,Wdq,Hdq
    0,
};

const ND_TABLE_EX_W gXopMap_mmmmm_09_opcode_95_w = 
{
    ND_ILUT_EX_W,
    0,
    {
        /* 00 */ (const void *)&gXopMap_mmmmm_09_opcode_95_w_00_leaf,
        /* 01 */ (const void *)&gXopMap_mmmmm_09_opcode_95_w_01_leaf,
    }
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_09_opcode_94_w_01_leaf = 
{
    ND_ILUT_INSTRUCTION,
    3866, // VPSHLB Vdq,Hdq,Wdq
    0,
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_09_opcode_94_w_00_leaf = 
{
    ND_ILUT_INSTRUCTION,
    3865, // VPSHLB Vdq,Wdq,Hdq
    0,
};

const ND_TABLE_EX_W gXopMap_mmmmm_09_opcode_94_w = 
{
    ND_ILUT_EX_W,
    0,
    {
        /* 00 */ (const void *)&gXopMap_mmmmm_09_opcode_94_w_00_leaf,
        /* 01 */ (const void *)&gXopMap_mmmmm_09_opcode_94_w_01_leaf,
    }
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_09_opcode_93_w_01_leaf = 
{
    ND_ILUT_INSTRUCTION,
    3847, // VPROTQ Vdq,Hdq,Wdq
    0,
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_09_opcode_93_w_00_leaf = 
{
    ND_ILUT_INSTRUCTION,
    3846, // VPROTQ Vdq,Wdq,Hdq
    0,
};

const ND_TABLE_EX_W gXopMap_mmmmm_09_opcode_93_w = 
{
    ND_ILUT_EX_W,
    0,
    {
        /* 00 */ (const void *)&gXopMap_mmmmm_09_opcode_93_w_00_leaf,
        /* 01 */ (const void *)&gXopMap_mmmmm_09_opcode_93_w_01_leaf,
    }
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_09_opcode_92_w_01_leaf = 
{
    ND_ILUT_INSTRUCTION,
    3844, // VPROTD Vdq,Hdq,Wdq
    0,
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_09_opcode_92_w_00_leaf = 
{
    ND_ILUT_INSTRUCTION,
    3843, // VPROTD Vdq,Wdq,Hdq
    0,
};

const ND_TABLE_EX_W gXopMap_mmmmm_09_opcode_92_w = 
{
    ND_ILUT_EX_W,
    0,
    {
        /* 00 */ (const void *)&gXopMap_mmmmm_09_opcode_92_w_00_leaf,
        /* 01 */ (const void *)&gXopMap_mmmmm_09_opcode_92_w_01_leaf,
    }
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_09_opcode_91_w_01_leaf = 
{
    ND_ILUT_INSTRUCTION,
    3850, // VPROTW Vdq,Hdq,Wdq
    0,
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_09_opcode_91_w_00_leaf = 
{
    ND_ILUT_INSTRUCTION,
    3849, // VPROTW Vdq,Wdq,Hdq
    0,
};

const ND_TABLE_EX_W gXopMap_mmmmm_09_opcode_91_w = 
{
    ND_ILUT_EX_W,
    0,
    {
        /* 00 */ (const void *)&gXopMap_mmmmm_09_opcode_91_w_00_leaf,
        /* 01 */ (const void *)&gXopMap_mmmmm_09_opcode_91_w_01_leaf,
    }
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_09_opcode_90_w_01_leaf = 
{
    ND_ILUT_INSTRUCTION,
    3841, // VPROTB Vdq,Hdq,Wdq
    0,
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_09_opcode_90_w_00_leaf = 
{
    ND_ILUT_INSTRUCTION,
    3840, // VPROTB Vdq,Wdq,Hdq
    0,
};

const ND_TABLE_EX_W gXopMap_mmmmm_09_opcode_90_w = 
{
    ND_ILUT_EX_W,
    0,
    {
        /* 00 */ (const void *)&gXopMap_mmmmm_09_opcode_90_w_00_leaf,
        /* 01 */ (const void *)&gXopMap_mmmmm_09_opcode_90_w_01_leaf,
    }
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_09_opcode_83_nov_00_leaf = 
{
    ND_ILUT_INSTRUCTION,
    3197, // VFRCZSD Vdq,Wsd
    0,
};

const ND_TABLE_FILTER gXopMap_mmmmm_09_opcode_83_nov = 
{
    ND_ILUT_FLT_NOV,
    0,
    {
        /* 00 */ (const void *)&gXopMap_mmmmm_09_opcode_83_nov_00_leaf,
    }
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_09_opcode_82_nov_00_leaf = 
{
    ND_ILUT_INSTRUCTION,
    3198, // VFRCZSS Vdq,Wss
    0,
};

const ND_TABLE_FILTER gXopMap_mmmmm_09_opcode_82_nov = 
{
    ND_ILUT_FLT_NOV,
    0,
    {
        /* 00 */ (const void *)&gXopMap_mmmmm_09_opcode_82_nov_00_leaf,
    }
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_09_opcode_81_nov_00_leaf = 
{
    ND_ILUT_INSTRUCTION,
    3195, // VFRCZPD Vx,Wx
    0,
};

const ND_TABLE_FILTER gXopMap_mmmmm_09_opcode_81_nov = 
{
    ND_ILUT_FLT_NOV,
    0,
    {
        /* 00 */ (const void *)&gXopMap_mmmmm_09_opcode_81_nov_00_leaf,
    }
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_09_opcode_80_nov_00_leaf = 
{
    ND_ILUT_INSTRUCTION,
    3196, // VFRCZPS Vx,Wx
    0,
};

const ND_TABLE_FILTER gXopMap_mmmmm_09_opcode_80_nov = 
{
    ND_ILUT_FLT_NOV,
    0,
    {
        /* 00 */ (const void *)&gXopMap_mmmmm_09_opcode_80_nov_00_leaf,
    }
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_09_opcode_12_modrmreg_01_modrmmod_01_nov_00_leaf = 
{
    ND_ILUT_INSTRUCTION,
    2521, // SLWPCB Ry
    0,
};

const ND_TABLE_FILTER gXopMap_mmmmm_09_opcode_12_modrmreg_01_modrmmod_01_nov = 
{
    ND_ILUT_FLT_NOV,
    0,
    {
        /* 00 */ (const void *)&gXopMap_mmmmm_09_opcode_12_modrmreg_01_modrmmod_01_nov_00_leaf,
    }
};

const ND_TABLE_MODRM_MOD gXopMap_mmmmm_09_opcode_12_modrmreg_01_modrmmod = 
{
    ND_ILUT_MODRM_MOD,
    0,
    {
        /* 00 */ (const void *)ND_NULL,
        /* 01 */ (const void *)&gXopMap_mmmmm_09_opcode_12_modrmreg_01_modrmmod_01_nov,
    }
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_09_opcode_12_modrmreg_00_modrmmod_01_nov_00_leaf = 
{
    ND_ILUT_INSTRUCTION,
    1317, // LLWPCB Ry
    0,
};

const ND_TABLE_FILTER gXopMap_mmmmm_09_opcode_12_modrmreg_00_modrmmod_01_nov = 
{
    ND_ILUT_FLT_NOV,
    0,
    {
        /* 00 */ (const void *)&gXopMap_mmmmm_09_opcode_12_modrmreg_00_modrmmod_01_nov_00_leaf,
    }
};

const ND_TABLE_MODRM_MOD gXopMap_mmmmm_09_opcode_12_modrmreg_00_modrmmod = 
{
    ND_ILUT_MODRM_MOD,
    0,
    {
        /* 00 */ (const void *)ND_NULL,
        /* 01 */ (const void *)&gXopMap_mmmmm_09_opcode_12_modrmreg_00_modrmmod_01_nov,
    }
};

const ND_TABLE_MODRM_REG gXopMap_mmmmm_09_opcode_12_modrmreg = 
{
    ND_ILUT_MODRM_REG,
    0,
    {
        /* 00 */ (const void *)&gXopMap_mmmmm_09_opcode_12_modrmreg_00_modrmmod,
        /* 01 */ (const void *)&gXopMap_mmmmm_09_opcode_12_modrmreg_01_modrmmod,
        /* 02 */ (const void *)ND_NULL,
        /* 03 */ (const void *)ND_NULL,
        /* 04 */ (const void *)ND_NULL,
        /* 05 */ (const void *)ND_NULL,
        /* 06 */ (const void *)ND_NULL,
        /* 07 */ (const void *)ND_NULL,
    }
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_09_opcode_02_modrmreg_06_leaf = 
{
    ND_ILUT_INSTRUCTION,
    191, // BLCI By,Ey
    0,
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_09_opcode_02_modrmreg_01_leaf = 
{
    ND_ILUT_INSTRUCTION,
    193, // BLCMSK By,Ey
    0,
};

const ND_TABLE_MODRM_REG gXopMap_mmmmm_09_opcode_02_modrmreg = 
{
    ND_ILUT_MODRM_REG,
    0,
    {
        /* 00 */ (const void *)ND_NULL,
        /* 01 */ (const void *)&gXopMap_mmmmm_09_opcode_02_modrmreg_01_leaf,
        /* 02 */ (const void *)ND_NULL,
        /* 03 */ (const void *)ND_NULL,
        /* 04 */ (const void *)ND_NULL,
        /* 05 */ (const void *)ND_NULL,
        /* 06 */ (const void *)&gXopMap_mmmmm_09_opcode_02_modrmreg_06_leaf,
        /* 07 */ (const void *)ND_NULL,
    }
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_09_opcode_01_modrmreg_07_leaf = 
{
    ND_ILUT_INSTRUCTION,
    2611, // T1MSKC By,Ey
    0,
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_09_opcode_01_modrmreg_06_leaf = 
{
    ND_ILUT_INSTRUCTION,
    202, // BLSIC By,Ey
    0,
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_09_opcode_01_modrmreg_05_leaf = 
{
    ND_ILUT_INSTRUCTION,
    192, // BLCIC By,Ey
    0,
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_09_opcode_01_modrmreg_04_leaf = 
{
    ND_ILUT_INSTRUCTION,
    2690, // TZMSK By,Ey
    0,
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_09_opcode_01_modrmreg_03_leaf = 
{
    ND_ILUT_INSTRUCTION,
    194, // BLCS By,Ey
    0,
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_09_opcode_01_modrmreg_02_leaf = 
{
    ND_ILUT_INSTRUCTION,
    199, // BLSFILL By,Ey
    0,
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_09_opcode_01_modrmreg_01_leaf = 
{
    ND_ILUT_INSTRUCTION,
    190, // BLCFILL By,Ey
    0,
};

const ND_TABLE_MODRM_REG gXopMap_mmmmm_09_opcode_01_modrmreg = 
{
    ND_ILUT_MODRM_REG,
    0,
    {
        /* 00 */ (const void *)ND_NULL,
        /* 01 */ (const void *)&gXopMap_mmmmm_09_opcode_01_modrmreg_01_leaf,
        /* 02 */ (const void *)&gXopMap_mmmmm_09_opcode_01_modrmreg_02_leaf,
        /* 03 */ (const void *)&gXopMap_mmmmm_09_opcode_01_modrmreg_03_leaf,
        /* 04 */ (const void *)&gXopMap_mmmmm_09_opcode_01_modrmreg_04_leaf,
        /* 05 */ (const void *)&gXopMap_mmmmm_09_opcode_01_modrmreg_05_leaf,
        /* 06 */ (const void *)&gXopMap_mmmmm_09_opcode_01_modrmreg_06_leaf,
        /* 07 */ (const void *)&gXopMap_mmmmm_09_opcode_01_modrmreg_07_leaf,
    }
};

const ND_TABLE_OPCODE gXopMap_mmmmm_09_opcode = 
{
    ND_ILUT_OPCODE,
    0,
    {
        /* 00 */ (const void *)ND_NULL,
        /* 01 */ (const void *)&gXopMap_mmmmm_09_opcode_01_modrmreg,
        /* 02 */ (const void *)&gXopMap_mmmmm_09_opcode_02_modrmreg,
        /* 03 */ (const void *)ND_NULL,
        /* 04 */ (const void *)ND_NULL,
        /* 05 */ (const void *)ND_NULL,
        /* 06 */ (const void *)ND_NULL,
        /* 07 */ (const void *)ND_NULL,
        /* 08 */ (const void *)ND_NULL,
        /* 09 */ (const void *)ND_NULL,
        /* 0a */ (const void *)ND_NULL,
        /* 0b */ (const void *)ND_NULL,
        /* 0c */ (const void *)ND_NULL,
        /* 0d */ (const void *)ND_NULL,
        /* 0e */ (const void *)ND_NULL,
        /* 0f */ (const void *)ND_NULL,
        /* 10 */ (const void *)ND_NULL,
        /* 11 */ (const void *)ND_NULL,
        /* 12 */ (const void *)&gXopMap_mmmmm_09_opcode_12_modrmreg,
        /* 13 */ (const void *)ND_NULL,
        /* 14 */ (const void *)ND_NULL,
        /* 15 */ (const void *)ND_NULL,
        /* 16 */ (const void *)ND_NULL,
        /* 17 */ (const void *)ND_NULL,
        /* 18 */ (const void *)ND_NULL,
        /* 19 */ (const void *)ND_NULL,
        /* 1a */ (const void *)ND_NULL,
        /* 1b */ (const void *)ND_NULL,
        /* 1c */ (const void *)ND_NULL,
        /* 1d */ (const void *)ND_NULL,
        /* 1e */ (const void *)ND_NULL,
        /* 1f */ (const void *)ND_NULL,
        /* 20 */ (const void *)ND_NULL,
        /* 21 */ (const void *)ND_NULL,
        /* 22 */ (const void *)ND_NULL,
        /* 23 */ (const void *)ND_NULL,
        /* 24 */ (const void *)ND_NULL,
        /* 25 */ (const void *)ND_NULL,
        /* 26 */ (const void *)ND_NULL,
        /* 27 */ (const void *)ND_NULL,
        /* 28 */ (const void *)ND_NULL,
        /* 29 */ (const void *)ND_NULL,
        /* 2a */ (const void *)ND_NULL,
        /* 2b */ (const void *)ND_NULL,
        /* 2c */ (const void *)ND_NULL,
        /* 2d */ (const void *)ND_NULL,
        /* 2e */ (const void *)ND_NULL,
        /* 2f */ (const void *)ND_NULL,
        /* 30 */ (const void *)ND_NULL,
        /* 31 */ (const void *)ND_NULL,
        /* 32 */ (const void *)ND_NULL,
        /* 33 */ (const void *)ND_NULL,
        /* 34 */ (const void *)ND_NULL,
        /* 35 */ (const void *)ND_NULL,
        /* 36 */ (const void *)ND_NULL,
        /* 37 */ (const void *)ND_NULL,
        /* 38 */ (const void *)ND_NULL,
        /* 39 */ (const void *)ND_NULL,
        /* 3a */ (const void *)ND_NULL,
        /* 3b */ (const void *)ND_NULL,
        /* 3c */ (const void *)ND_NULL,
        /* 3d */ (const void *)ND_NULL,
        /* 3e */ (const void *)ND_NULL,
        /* 3f */ (const void *)ND_NULL,
        /* 40 */ (const void *)ND_NULL,
        /* 41 */ (const void *)ND_NULL,
        /* 42 */ (const void *)ND_NULL,
        /* 43 */ (const void *)ND_NULL,
        /* 44 */ (const void *)ND_NULL,
        /* 45 */ (const void *)ND_NULL,
        /* 46 */ (const void *)ND_NULL,
        /* 47 */ (const void *)ND_NULL,
        /* 48 */ (const void *)ND_NULL,
        /* 49 */ (const void *)ND_NULL,
        /* 4a */ (const void *)ND_NULL,
        /* 4b */ (const void *)ND_NULL,
        /* 4c */ (const void *)ND_NULL,
        /* 4d */ (const void *)ND_NULL,
        /* 4e */ (const void *)ND_NULL,
        /* 4f */ (const void *)ND_NULL,
        /* 50 */ (const void *)ND_NULL,
        /* 51 */ (const void *)ND_NULL,
        /* 52 */ (const void *)ND_NULL,
        /* 53 */ (const void *)ND_NULL,
        /* 54 */ (const void *)ND_NULL,
        /* 55 */ (const void *)ND_NULL,
        /* 56 */ (const void *)ND_NULL,
        /* 57 */ (const void *)ND_NULL,
        /* 58 */ (const void *)ND_NULL,
        /* 59 */ (const void *)ND_NULL,
        /* 5a */ (const void *)ND_NULL,
        /* 5b */ (const void *)ND_NULL,
        /* 5c */ (const void *)ND_NULL,
        /* 5d */ (const void *)ND_NULL,
        /* 5e */ (const void *)ND_NULL,
        /* 5f */ (const void *)ND_NULL,
        /* 60 */ (const void *)ND_NULL,
        /* 61 */ (const void *)ND_NULL,
        /* 62 */ (const void *)ND_NULL,
        /* 63 */ (const void *)ND_NULL,
        /* 64 */ (const void *)ND_NULL,
        /* 65 */ (const void *)ND_NULL,
        /* 66 */ (const void *)ND_NULL,
        /* 67 */ (const void *)ND_NULL,
        /* 68 */ (const void *)ND_NULL,
        /* 69 */ (const void *)ND_NULL,
        /* 6a */ (const void *)ND_NULL,
        /* 6b */ (const void *)ND_NULL,
        /* 6c */ (const void *)ND_NULL,
        /* 6d */ (const void *)ND_NULL,
        /* 6e */ (const void *)ND_NULL,
        /* 6f */ (const void *)ND_NULL,
        /* 70 */ (const void *)ND_NULL,
        /* 71 */ (const void *)ND_NULL,
        /* 72 */ (const void *)ND_NULL,
        /* 73 */ (const void *)ND_NULL,
        /* 74 */ (const void *)ND_NULL,
        /* 75 */ (const void *)ND_NULL,
        /* 76 */ (const void *)ND_NULL,
        /* 77 */ (const void *)ND_NULL,
        /* 78 */ (const void *)ND_NULL,
        /* 79 */ (const void *)ND_NULL,
        /* 7a */ (const void *)ND_NULL,
        /* 7b */ (const void *)ND_NULL,
        /* 7c */ (const void *)ND_NULL,
        /* 7d */ (const void *)ND_NULL,
        /* 7e */ (const void *)ND_NULL,
        /* 7f */ (const void *)ND_NULL,
        /* 80 */ (const void *)&gXopMap_mmmmm_09_opcode_80_nov,
        /* 81 */ (const void *)&gXopMap_mmmmm_09_opcode_81_nov,
        /* 82 */ (const void *)&gXopMap_mmmmm_09_opcode_82_nov,
        /* 83 */ (const void *)&gXopMap_mmmmm_09_opcode_83_nov,
        /* 84 */ (const void *)ND_NULL,
        /* 85 */ (const void *)ND_NULL,
        /* 86 */ (const void *)ND_NULL,
        /* 87 */ (const void *)ND_NULL,
        /* 88 */ (const void *)ND_NULL,
        /* 89 */ (const void *)ND_NULL,
        /* 8a */ (const void *)ND_NULL,
        /* 8b */ (const void *)ND_NULL,
        /* 8c */ (const void *)ND_NULL,
        /* 8d */ (const void *)ND_NULL,
        /* 8e */ (const void *)ND_NULL,
        /* 8f */ (const void *)ND_NULL,
        /* 90 */ (const void *)&gXopMap_mmmmm_09_opcode_90_w,
        /* 91 */ (const void *)&gXopMap_mmmmm_09_opcode_91_w,
        /* 92 */ (const void *)&gXopMap_mmmmm_09_opcode_92_w,
        /* 93 */ (const void *)&gXopMap_mmmmm_09_opcode_93_w,
        /* 94 */ (const void *)&gXopMap_mmmmm_09_opcode_94_w,
        /* 95 */ (const void *)&gXopMap_mmmmm_09_opcode_95_w,
        /* 96 */ (const void *)&gXopMap_mmmmm_09_opcode_96_w,
        /* 97 */ (const void *)&gXopMap_mmmmm_09_opcode_97_w,
        /* 98 */ (const void *)&gXopMap_mmmmm_09_opcode_98_w,
        /* 99 */ (const void *)&gXopMap_mmmmm_09_opcode_99_w,
        /* 9a */ (const void *)&gXopMap_mmmmm_09_opcode_9a_w,
        /* 9b */ (const void *)&gXopMap_mmmmm_09_opcode_9b_w,
        /* 9c */ (const void *)ND_NULL,
        /* 9d */ (const void *)ND_NULL,
        /* 9e */ (const void *)ND_NULL,
        /* 9f */ (const void *)ND_NULL,
        /* a0 */ (const void *)ND_NULL,
        /* a1 */ (const void *)ND_NULL,
        /* a2 */ (const void *)ND_NULL,
        /* a3 */ (const void *)ND_NULL,
        /* a4 */ (const void *)ND_NULL,
        /* a5 */ (const void *)ND_NULL,
        /* a6 */ (const void *)ND_NULL,
        /* a7 */ (const void *)ND_NULL,
        /* a8 */ (const void *)ND_NULL,
        /* a9 */ (const void *)ND_NULL,
        /* aa */ (const void *)ND_NULL,
        /* ab */ (const void *)ND_NULL,
        /* ac */ (const void *)ND_NULL,
        /* ad */ (const void *)ND_NULL,
        /* ae */ (const void *)ND_NULL,
        /* af */ (const void *)ND_NULL,
        /* b0 */ (const void *)ND_NULL,
        /* b1 */ (const void *)ND_NULL,
        /* b2 */ (const void *)ND_NULL,
        /* b3 */ (const void *)ND_NULL,
        /* b4 */ (const void *)ND_NULL,
        /* b5 */ (const void *)ND_NULL,
        /* b6 */ (const void *)ND_NULL,
        /* b7 */ (const void *)ND_NULL,
        /* b8 */ (const void *)ND_NULL,
        /* b9 */ (const void *)ND_NULL,
        /* ba */ (const void *)ND_NULL,
        /* bb */ (const void *)ND_NULL,
        /* bc */ (const void *)ND_NULL,
        /* bd */ (const void *)ND_NULL,
        /* be */ (const void *)ND_NULL,
        /* bf */ (const void *)ND_NULL,
        /* c0 */ (const void *)ND_NULL,
        /* c1 */ (const void *)&gXopMap_mmmmm_09_opcode_c1_nov,
        /* c2 */ (const void *)&gXopMap_mmmmm_09_opcode_c2_nov,
        /* c3 */ (const void *)&gXopMap_mmmmm_09_opcode_c3_nov,
        /* c4 */ (const void *)ND_NULL,
        /* c5 */ (const void *)ND_NULL,
        /* c6 */ (const void *)&gXopMap_mmmmm_09_opcode_c6_nov,
        /* c7 */ (const void *)&gXopMap_mmmmm_09_opcode_c7_nov,
        /* c8 */ (const void *)ND_NULL,
        /* c9 */ (const void *)ND_NULL,
        /* ca */ (const void *)ND_NULL,
        /* cb */ (const void *)&gXopMap_mmmmm_09_opcode_cb_nov,
        /* cc */ (const void *)ND_NULL,
        /* cd */ (const void *)ND_NULL,
        /* ce */ (const void *)ND_NULL,
        /* cf */ (const void *)ND_NULL,
        /* d0 */ (const void *)ND_NULL,
        /* d1 */ (const void *)&gXopMap_mmmmm_09_opcode_d1_nov,
        /* d2 */ (const void *)&gXopMap_mmmmm_09_opcode_d2_nov,
        /* d3 */ (const void *)&gXopMap_mmmmm_09_opcode_d3_nov,
        /* d4 */ (const void *)ND_NULL,
        /* d5 */ (const void *)ND_NULL,
        /* d6 */ (const void *)&gXopMap_mmmmm_09_opcode_d6_nov,
        /* d7 */ (const void *)&gXopMap_mmmmm_09_opcode_d7_nov,
        /* d8 */ (const void *)ND_NULL,
        /* d9 */ (const void *)ND_NULL,
        /* da */ (const void *)ND_NULL,
        /* db */ (const void *)&gXopMap_mmmmm_09_opcode_db_nov,
        /* dc */ (const void *)ND_NULL,
        /* dd */ (const void *)ND_NULL,
        /* de */ (const void *)ND_NULL,
        /* df */ (const void *)ND_NULL,
        /* e0 */ (const void *)ND_NULL,
        /* e1 */ (const void *)&gXopMap_mmmmm_09_opcode_e1_nov,
        /* e2 */ (const void *)&gXopMap_mmmmm_09_opcode_e2_nov,
        /* e3 */ (const void *)&gXopMap_mmmmm_09_opcode_e3_nov,
        /* e4 */ (const void *)ND_NULL,
        /* e5 */ (const void *)ND_NULL,
        /* e6 */ (const void *)ND_NULL,
        /* e7 */ (const void *)ND_NULL,
        /* e8 */ (const void *)ND_NULL,
        /* e9 */ (const void *)ND_NULL,
        /* ea */ (const void *)ND_NULL,
        /* eb */ (const void *)ND_NULL,
        /* ec */ (const void *)ND_NULL,
        /* ed */ (const void *)ND_NULL,
        /* ee */ (const void *)ND_NULL,
        /* ef */ (const void *)ND_NULL,
        /* f0 */ (const void *)ND_NULL,
        /* f1 */ (const void *)ND_NULL,
        /* f2 */ (const void *)ND_NULL,
        /* f3 */ (const void *)ND_NULL,
        /* f4 */ (const void *)ND_NULL,
        /* f5 */ (const void *)ND_NULL,
        /* f6 */ (const void *)ND_NULL,
        /* f7 */ (const void *)ND_NULL,
        /* f8 */ (const void *)ND_NULL,
        /* f9 */ (const void *)ND_NULL,
        /* fa */ (const void *)ND_NULL,
        /* fb */ (const void *)ND_NULL,
        /* fc */ (const void *)ND_NULL,
        /* fd */ (const void *)ND_NULL,
        /* fe */ (const void *)ND_NULL,
        /* ff */ (const void *)ND_NULL,
    }
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_08_opcode_ef_leaf = 
{
    ND_ILUT_INSTRUCTION,
    3548, // VPCOMUQ Vdq,Hdq,Wdq,Ib
    0,
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_08_opcode_ee_leaf = 
{
    ND_ILUT_INSTRUCTION,
    3547, // VPCOMUD Vdq,Hdq,Wdq,Ib
    0,
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_08_opcode_ed_leaf = 
{
    ND_ILUT_INSTRUCTION,
    3549, // VPCOMUW Vdq,Hdq,Wdq,Ib
    0,
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_08_opcode_ec_leaf = 
{
    ND_ILUT_INSTRUCTION,
    3546, // VPCOMUB Vdq,Hdq,Wdq,Ib
    0,
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_08_opcode_cf_leaf = 
{
    ND_ILUT_INSTRUCTION,
    3545, // VPCOMQ Vdq,Hdq,Wdq,Ib
    0,
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_08_opcode_ce_leaf = 
{
    ND_ILUT_INSTRUCTION,
    3540, // VPCOMD Vdq,Hdq,Wdq,Ib
    0,
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_08_opcode_cd_leaf = 
{
    ND_ILUT_INSTRUCTION,
    3550, // VPCOMW Vdq,Hdq,Wdq,Ib
    0,
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_08_opcode_cc_leaf = 
{
    ND_ILUT_INSTRUCTION,
    3539, // VPCOMB Vdq,Hdq,Wdq,Ib
    0,
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_08_opcode_c3_nov_00_leaf = 
{
    ND_ILUT_INSTRUCTION,
    3845, // VPROTQ Vdq,Wdq,Ib
    0,
};

const ND_TABLE_FILTER gXopMap_mmmmm_08_opcode_c3_nov = 
{
    ND_ILUT_FLT_NOV,
    0,
    {
        /* 00 */ (const void *)&gXopMap_mmmmm_08_opcode_c3_nov_00_leaf,
    }
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_08_opcode_c2_nov_00_leaf = 
{
    ND_ILUT_INSTRUCTION,
    3842, // VPROTD Vdq,Wdq,Ib
    0,
};

const ND_TABLE_FILTER gXopMap_mmmmm_08_opcode_c2_nov = 
{
    ND_ILUT_FLT_NOV,
    0,
    {
        /* 00 */ (const void *)&gXopMap_mmmmm_08_opcode_c2_nov_00_leaf,
    }
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_08_opcode_c1_nov_00_leaf = 
{
    ND_ILUT_INSTRUCTION,
    3848, // VPROTW Vdq,Wdq,Ib
    0,
};

const ND_TABLE_FILTER gXopMap_mmmmm_08_opcode_c1_nov = 
{
    ND_ILUT_FLT_NOV,
    0,
    {
        /* 00 */ (const void *)&gXopMap_mmmmm_08_opcode_c1_nov_00_leaf,
    }
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_08_opcode_c0_nov_00_leaf = 
{
    ND_ILUT_INSTRUCTION,
    3839, // VPROTB Vdq,Wdq,Ib
    0,
};

const ND_TABLE_FILTER gXopMap_mmmmm_08_opcode_c0_nov = 
{
    ND_ILUT_FLT_NOV,
    0,
    {
        /* 00 */ (const void *)&gXopMap_mmmmm_08_opcode_c0_nov_00_leaf,
    }
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_08_opcode_b6_leaf = 
{
    ND_ILUT_INSTRUCTION,
    3702, // VPMADCSWD Vdq,Hdq,Wdq,Ldq
    0,
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_08_opcode_a6_leaf = 
{
    ND_ILUT_INSTRUCTION,
    3701, // VPMADCSSWD Vdq,Hdq,Wdq,Ldq
    0,
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_08_opcode_a3_w_01_leaf = 
{
    ND_ILUT_INSTRUCTION,
    3830, // VPPERM Vx,Hx,Lx,Wx
    0,
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_08_opcode_a3_w_00_leaf = 
{
    ND_ILUT_INSTRUCTION,
    3829, // VPPERM Vx,Hx,Wx,Lx
    0,
};

const ND_TABLE_EX_W gXopMap_mmmmm_08_opcode_a3_w = 
{
    ND_ILUT_EX_W,
    0,
    {
        /* 00 */ (const void *)&gXopMap_mmmmm_08_opcode_a3_w_00_leaf,
        /* 01 */ (const void *)&gXopMap_mmmmm_08_opcode_a3_w_01_leaf,
    }
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_08_opcode_a2_w_01_leaf = 
{
    ND_ILUT_INSTRUCTION,
    3510, // VPCMOV Vx,Hx,Lx,Wx
    0,
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_08_opcode_a2_w_00_leaf = 
{
    ND_ILUT_INSTRUCTION,
    3509, // VPCMOV Vx,Hx,Wx,Lx
    0,
};

const ND_TABLE_EX_W gXopMap_mmmmm_08_opcode_a2_w = 
{
    ND_ILUT_EX_W,
    0,
    {
        /* 00 */ (const void *)&gXopMap_mmmmm_08_opcode_a2_w_00_leaf,
        /* 01 */ (const void *)&gXopMap_mmmmm_08_opcode_a2_w_01_leaf,
    }
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_08_opcode_9f_leaf = 
{
    ND_ILUT_INSTRUCTION,
    3692, // VPMACSDQH Vdq,Hdq,Wdq,Ldq
    0,
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_08_opcode_9e_leaf = 
{
    ND_ILUT_INSTRUCTION,
    3691, // VPMACSDD Vdq,Hdq,Wdq,Ldq
    0,
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_08_opcode_97_leaf = 
{
    ND_ILUT_INSTRUCTION,
    3693, // VPMACSDQL Vdq,Hdq,Wdq,Ldq
    0,
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_08_opcode_96_leaf = 
{
    ND_ILUT_INSTRUCTION,
    3699, // VPMACSWD Vdq,Hdq,Wdq,Ldq
    0,
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_08_opcode_95_leaf = 
{
    ND_ILUT_INSTRUCTION,
    3700, // VPMACSWW Vdq,Hdq,Wdq,Ldq
    0,
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_08_opcode_8f_leaf = 
{
    ND_ILUT_INSTRUCTION,
    3695, // VPMACSSDQH Vdq,Hdq,Wdq,Ldq
    0,
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_08_opcode_8e_leaf = 
{
    ND_ILUT_INSTRUCTION,
    3694, // VPMACSSDD Vdq,Hdq,Wdq,Ldq
    0,
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_08_opcode_87_leaf = 
{
    ND_ILUT_INSTRUCTION,
    3696, // VPMACSSDQL Vdq,Hdq,Wdq,Ldq
    0,
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_08_opcode_86_leaf = 
{
    ND_ILUT_INSTRUCTION,
    3697, // VPMACSSWD Vdq,Hdq,Wdq,Ldq
    0,
};

const ND_TABLE_INSTRUCTION gXopMap_mmmmm_08_opcode_85_leaf = 
{
    ND_ILUT_INSTRUCTION,
    3698, // VPMACSSWW Vdq,Hdq,Wdq,Ldq
    0,
};

const ND_TABLE_OPCODE gXopMap_mmmmm_08_opcode = 
{
    ND_ILUT_OPCODE,
    0,
    {
        /* 00 */ (const void *)ND_NULL,
        /* 01 */ (const void *)ND_NULL,
        /* 02 */ (const void *)ND_NULL,
        /* 03 */ (const void *)ND_NULL,
        /* 04 */ (const void *)ND_NULL,
        /* 05 */ (const void *)ND_NULL,
        /* 06 */ (const void *)ND_NULL,
        /* 07 */ (const void *)ND_NULL,
        /* 08 */ (const void *)ND_NULL,
        /* 09 */ (const void *)ND_NULL,
        /* 0a */ (const void *)ND_NULL,
        /* 0b */ (const void *)ND_NULL,
        /* 0c */ (const void *)ND_NULL,
        /* 0d */ (const void *)ND_NULL,
        /* 0e */ (const void *)ND_NULL,
        /* 0f */ (const void *)ND_NULL,
        /* 10 */ (const void *)ND_NULL,
        /* 11 */ (const void *)ND_NULL,
        /* 12 */ (const void *)ND_NULL,
        /* 13 */ (const void *)ND_NULL,
        /* 14 */ (const void *)ND_NULL,
        /* 15 */ (const void *)ND_NULL,
        /* 16 */ (const void *)ND_NULL,
        /* 17 */ (const void *)ND_NULL,
        /* 18 */ (const void *)ND_NULL,
        /* 19 */ (const void *)ND_NULL,
        /* 1a */ (const void *)ND_NULL,
        /* 1b */ (const void *)ND_NULL,
        /* 1c */ (const void *)ND_NULL,
        /* 1d */ (const void *)ND_NULL,
        /* 1e */ (const void *)ND_NULL,
        /* 1f */ (const void *)ND_NULL,
        /* 20 */ (const void *)ND_NULL,
        /* 21 */ (const void *)ND_NULL,
        /* 22 */ (const void *)ND_NULL,
        /* 23 */ (const void *)ND_NULL,
        /* 24 */ (const void *)ND_NULL,
        /* 25 */ (const void *)ND_NULL,
        /* 26 */ (const void *)ND_NULL,
        /* 27 */ (const void *)ND_NULL,
        /* 28 */ (const void *)ND_NULL,
        /* 29 */ (const void *)ND_NULL,
        /* 2a */ (const void *)ND_NULL,
        /* 2b */ (const void *)ND_NULL,
        /* 2c */ (const void *)ND_NULL,
        /* 2d */ (const void *)ND_NULL,
        /* 2e */ (const void *)ND_NULL,
        /* 2f */ (const void *)ND_NULL,
        /* 30 */ (const void *)ND_NULL,
        /* 31 */ (const void *)ND_NULL,
        /* 32 */ (const void *)ND_NULL,
        /* 33 */ (const void *)ND_NULL,
        /* 34 */ (const void *)ND_NULL,
        /* 35 */ (const void *)ND_NULL,
        /* 36 */ (const void *)ND_NULL,
        /* 37 */ (const void *)ND_NULL,
        /* 38 */ (const void *)ND_NULL,
        /* 39 */ (const void *)ND_NULL,
        /* 3a */ (const void *)ND_NULL,
        /* 3b */ (const void *)ND_NULL,
        /* 3c */ (const void *)ND_NULL,
        /* 3d */ (const void *)ND_NULL,
        /* 3e */ (const void *)ND_NULL,
        /* 3f */ (const void *)ND_NULL,
        /* 40 */ (const void *)ND_NULL,
        /* 41 */ (const void *)ND_NULL,
        /* 42 */ (const void *)ND_NULL,
        /* 43 */ (const void *)ND_NULL,
        /* 44 */ (const void *)ND_NULL,
        /* 45 */ (const void *)ND_NULL,
        /* 46 */ (const void *)ND_NULL,
        /* 47 */ (const void *)ND_NULL,
        /* 48 */ (const void *)ND_NULL,
        /* 49 */ (const void *)ND_NULL,
        /* 4a */ (const void *)ND_NULL,
        /* 4b */ (const void *)ND_NULL,
        /* 4c */ (const void *)ND_NULL,
        /* 4d */ (const void *)ND_NULL,
        /* 4e */ (const void *)ND_NULL,
        /* 4f */ (const void *)ND_NULL,
        /* 50 */ (const void *)ND_NULL,
        /* 51 */ (const void *)ND_NULL,
        /* 52 */ (const void *)ND_NULL,
        /* 53 */ (const void *)ND_NULL,
        /* 54 */ (const void *)ND_NULL,
        /* 55 */ (const void *)ND_NULL,
        /* 56 */ (const void *)ND_NULL,
        /* 57 */ (const void *)ND_NULL,
        /* 58 */ (const void *)ND_NULL,
        /* 59 */ (const void *)ND_NULL,
        /* 5a */ (const void *)ND_NULL,
        /* 5b */ (const void *)ND_NULL,
        /* 5c */ (const void *)ND_NULL,
        /* 5d */ (const void *)ND_NULL,
        /* 5e */ (const void *)ND_NULL,
        /* 5f */ (const void *)ND_NULL,
        /* 60 */ (const void *)ND_NULL,
        /* 61 */ (const void *)ND_NULL,
        /* 62 */ (const void *)ND_NULL,
        /* 63 */ (const void *)ND_NULL,
        /* 64 */ (const void *)ND_NULL,
        /* 65 */ (const void *)ND_NULL,
        /* 66 */ (const void *)ND_NULL,
        /* 67 */ (const void *)ND_NULL,
        /* 68 */ (const void *)ND_NULL,
        /* 69 */ (const void *)ND_NULL,
        /* 6a */ (const void *)ND_NULL,
        /* 6b */ (const void *)ND_NULL,
        /* 6c */ (const void *)ND_NULL,
        /* 6d */ (const void *)ND_NULL,
        /* 6e */ (const void *)ND_NULL,
        /* 6f */ (const void *)ND_NULL,
        /* 70 */ (const void *)ND_NULL,
        /* 71 */ (const void *)ND_NULL,
        /* 72 */ (const void *)ND_NULL,
        /* 73 */ (const void *)ND_NULL,
        /* 74 */ (const void *)ND_NULL,
        /* 75 */ (const void *)ND_NULL,
        /* 76 */ (const void *)ND_NULL,
        /* 77 */ (const void *)ND_NULL,
        /* 78 */ (const void *)ND_NULL,
        /* 79 */ (const void *)ND_NULL,
        /* 7a */ (const void *)ND_NULL,
        /* 7b */ (const void *)ND_NULL,
        /* 7c */ (const void *)ND_NULL,
        /* 7d */ (const void *)ND_NULL,
        /* 7e */ (const void *)ND_NULL,
        /* 7f */ (const void *)ND_NULL,
        /* 80 */ (const void *)ND_NULL,
        /* 81 */ (const void *)ND_NULL,
        /* 82 */ (const void *)ND_NULL,
        /* 83 */ (const void *)ND_NULL,
        /* 84 */ (const void *)ND_NULL,
        /* 85 */ (const void *)&gXopMap_mmmmm_08_opcode_85_leaf,
        /* 86 */ (const void *)&gXopMap_mmmmm_08_opcode_86_leaf,
        /* 87 */ (const void *)&gXopMap_mmmmm_08_opcode_87_leaf,
        /* 88 */ (const void *)ND_NULL,
        /* 89 */ (const void *)ND_NULL,
        /* 8a */ (const void *)ND_NULL,
        /* 8b */ (const void *)ND_NULL,
        /* 8c */ (const void *)ND_NULL,
        /* 8d */ (const void *)ND_NULL,
        /* 8e */ (const void *)&gXopMap_mmmmm_08_opcode_8e_leaf,
        /* 8f */ (const void *)&gXopMap_mmmmm_08_opcode_8f_leaf,
        /* 90 */ (const void *)ND_NULL,
        /* 91 */ (const void *)ND_NULL,
        /* 92 */ (const void *)ND_NULL,
        /* 93 */ (const void *)ND_NULL,
        /* 94 */ (const void *)ND_NULL,
        /* 95 */ (const void *)&gXopMap_mmmmm_08_opcode_95_leaf,
        /* 96 */ (const void *)&gXopMap_mmmmm_08_opcode_96_leaf,
        /* 97 */ (const void *)&gXopMap_mmmmm_08_opcode_97_leaf,
        /* 98 */ (const void *)ND_NULL,
        /* 99 */ (const void *)ND_NULL,
        /* 9a */ (const void *)ND_NULL,
        /* 9b */ (const void *)ND_NULL,
        /* 9c */ (const void *)ND_NULL,
        /* 9d */ (const void *)ND_NULL,
        /* 9e */ (const void *)&gXopMap_mmmmm_08_opcode_9e_leaf,
        /* 9f */ (const void *)&gXopMap_mmmmm_08_opcode_9f_leaf,
        /* a0 */ (const void *)ND_NULL,
        /* a1 */ (const void *)ND_NULL,
        /* a2 */ (const void *)&gXopMap_mmmmm_08_opcode_a2_w,
        /* a3 */ (const void *)&gXopMap_mmmmm_08_opcode_a3_w,
        /* a4 */ (const void *)ND_NULL,
        /* a5 */ (const void *)ND_NULL,
        /* a6 */ (const void *)&gXopMap_mmmmm_08_opcode_a6_leaf,
        /* a7 */ (const void *)ND_NULL,
        /* a8 */ (const void *)ND_NULL,
        /* a9 */ (const void *)ND_NULL,
        /* aa */ (const void *)ND_NULL,
        /* ab */ (const void *)ND_NULL,
        /* ac */ (const void *)ND_NULL,
        /* ad */ (const void *)ND_NULL,
        /* ae */ (const void *)ND_NULL,
        /* af */ (const void *)ND_NULL,
        /* b0 */ (const void *)ND_NULL,
        /* b1 */ (const void *)ND_NULL,
        /* b2 */ (const void *)ND_NULL,
        /* b3 */ (const void *)ND_NULL,
        /* b4 */ (const void *)ND_NULL,
        /* b5 */ (const void *)ND_NULL,
        /* b6 */ (const void *)&gXopMap_mmmmm_08_opcode_b6_leaf,
        /* b7 */ (const void *)ND_NULL,
        /* b8 */ (const void *)ND_NULL,
        /* b9 */ (const void *)ND_NULL,
        /* ba */ (const void *)ND_NULL,
        /* bb */ (const void *)ND_NULL,
        /* bc */ (const void *)ND_NULL,
        /* bd */ (const void *)ND_NULL,
        /* be */ (const void *)ND_NULL,
        /* bf */ (const void *)ND_NULL,
        /* c0 */ (const void *)&gXopMap_mmmmm_08_opcode_c0_nov,
        /* c1 */ (const void *)&gXopMap_mmmmm_08_opcode_c1_nov,
        /* c2 */ (const void *)&gXopMap_mmmmm_08_opcode_c2_nov,
        /* c3 */ (const void *)&gXopMap_mmmmm_08_opcode_c3_nov,
        /* c4 */ (const void *)ND_NULL,
        /* c5 */ (const void *)ND_NULL,
        /* c6 */ (const void *)ND_NULL,
        /* c7 */ (const void *)ND_NULL,
        /* c8 */ (const void *)ND_NULL,
        /* c9 */ (const void *)ND_NULL,
        /* ca */ (const void *)ND_NULL,
        /* cb */ (const void *)ND_NULL,
        /* cc */ (const void *)&gXopMap_mmmmm_08_opcode_cc_leaf,
        /* cd */ (const void *)&gXopMap_mmmmm_08_opcode_cd_leaf,
        /* ce */ (const void *)&gXopMap_mmmmm_08_opcode_ce_leaf,
        /* cf */ (const void *)&gXopMap_mmmmm_08_opcode_cf_leaf,
        /* d0 */ (const void *)ND_NULL,
        /* d1 */ (const void *)ND_NULL,
        /* d2 */ (const void *)ND_NULL,
        /* d3 */ (const void *)ND_NULL,
        /* d4 */ (const void *)ND_NULL,
        /* d5 */ (const void *)ND_NULL,
        /* d6 */ (const void *)ND_NULL,
        /* d7 */ (const void *)ND_NULL,
        /* d8 */ (const void *)ND_NULL,
        /* d9 */ (const void *)ND_NULL,
        /* da */ (const void *)ND_NULL,
        /* db */ (const void *)ND_NULL,
        /* dc */ (const void *)ND_NULL,
        /* dd */ (const void *)ND_NULL,
        /* de */ (const void *)ND_NULL,
        /* df */ (const void *)ND_NULL,
        /* e0 */ (const void *)ND_NULL,
        /* e1 */ (const void *)ND_NULL,
        /* e2 */ (const void *)ND_NULL,
        /* e3 */ (const void *)ND_NULL,
        /* e4 */ (const void *)ND_NULL,
        /* e5 */ (const void *)ND_NULL,
        /* e6 */ (const void *)ND_NULL,
        /* e7 */ (const void *)ND_NULL,
        /* e8 */ (const void *)ND_NULL,
        /* e9 */ (const void *)ND_NULL,
        /* ea */ (const void *)ND_NULL,
        /* eb */ (const void *)ND_NULL,
        /* ec */ (const void *)&gXopMap_mmmmm_08_opcode_ec_leaf,
        /* ed */ (const void *)&gXopMap_mmmmm_08_opcode_ed_leaf,
        /* ee */ (const void *)&gXopMap_mmmmm_08_opcode_ee_leaf,
        /* ef */ (const void *)&gXopMap_mmmmm_08_opcode_ef_leaf,
        /* f0 */ (const void *)ND_NULL,
        /* f1 */ (const void *)ND_NULL,
        /* f2 */ (const void *)ND_NULL,
        /* f3 */ (const void *)ND_NULL,
        /* f4 */ (const void *)ND_NULL,
        /* f5 */ (const void *)ND_NULL,
        /* f6 */ (const void *)ND_NULL,
        /* f7 */ (const void *)ND_NULL,
        /* f8 */ (const void *)ND_NULL,
        /* f9 */ (const void *)ND_NULL,
        /* fa */ (const void *)ND_NULL,
        /* fb */ (const void *)ND_NULL,
        /* fc */ (const void *)ND_NULL,
        /* fd */ (const void *)ND_NULL,
        /* fe */ (const void *)ND_NULL,
        /* ff */ (const void *)ND_NULL,
    }
};

const ND_TABLE_EX_M gXopMap_mmmmm = 
{
    ND_ILUT_EX_M,
    0,
    {
        /* 00 */ (const void *)ND_NULL,
        /* 01 */ (const void *)ND_NULL,
        /* 02 */ (const void *)ND_NULL,
        /* 03 */ (const void *)ND_NULL,
        /* 04 */ (const void *)ND_NULL,
        /* 05 */ (const void *)ND_NULL,
        /* 06 */ (const void *)ND_NULL,
        /* 07 */ (const void *)ND_NULL,
        /* 08 */ (const void *)&gXopMap_mmmmm_08_opcode,
        /* 09 */ (const void *)&gXopMap_mmmmm_09_opcode,
        /* 0a */ (const void *)&gXopMap_mmmmm_0a_opcode,
        /* 0b */ (const void *)ND_NULL,
        /* 0c */ (const void *)ND_NULL,
        /* 0d */ (const void *)ND_NULL,
        /* 0e */ (const void *)ND_NULL,
        /* 0f */ (const void *)ND_NULL,
        /* 10 */ (const void *)ND_NULL,
        /* 11 */ (const void *)ND_NULL,
        /* 12 */ (const void *)ND_NULL,
        /* 13 */ (const void *)ND_NULL,
        /* 14 */ (const void *)ND_NULL,
        /* 15 */ (const void *)ND_NULL,
        /* 16 */ (const void *)ND_NULL,
        /* 17 */ (const void *)ND_NULL,
        /* 18 */ (const void *)ND_NULL,
        /* 19 */ (const void *)ND_NULL,
        /* 1a */ (const void *)ND_NULL,
        /* 1b */ (const void *)ND_NULL,
        /* 1c */ (const void *)ND_NULL,
        /* 1d */ (const void *)ND_NULL,
        /* 1e */ (const void *)ND_NULL,
        /* 1f */ (const void *)ND_NULL,
    }
};


#endif

