    bits 64
    
    movupd         xmm7,xmm13       
    movsd          xmm7,xmm13       
    movupd         xmm13,xmm7       
    movsd          xmm13,xmm7       
    movlpd         xmm7,[rbx]        
    movlpd         [rbx],xmm7        
    unpcklpd       xmm7,xmm13         
    unpckhpd       xmm7,xmm13         
    movhpd         xmm7,[rbx]         
    movhpd         [rbx],xmm7         
    movapd         xmm7,xmm13       
    movapd         xmm13,xmm7       
    cvtsi2sd       xmm7,edx        
    cvtsi2sd       xmm7,rdx
    movntpd        [rbx],xmm7       
    cvttsd2si      edx,xmm13        
    cvttsd2si      rdx,xmm13        
    cvtsd2si       edx,xmm13        
    cvtsd2si       rdx,xmm13        
    ucomisd        xmm7,xmm13       
    comisd         xmm7,xmm13       
    movmskpd       eax,xmm7
    sqrtpd         xmm7,xmm13       
    sqrtsd         xmm7,xmm13       
    andpd          xmm7,xmm13       
    andnpd         xmm7,xmm13       
    orpd           xmm7,xmm13       
    xorpd          xmm7,xmm13       
    addpd          xmm7,xmm13       
    addsd          xmm7,xmm13       
    mulpd          xmm7,xmm13       
    mulsd          xmm7,xmm13       
    cvtps2pd       xmm7,xmm13        
    cvtpd2ps       xmm7,xmm13       
    cvtss2sd       xmm7,xmm13       
    cvtsd2ss       xmm7,xmm13       
    cvtdq2ps       xmm7,xmm13       
    cvtps2dq       xmm7,xmm13       
    cvttps2dq      xmm7,xmm13       
    subpd          xmm7,xmm13       
    subsd          xmm7,xmm13       
    minpd          xmm7,xmm13       
    minsd          xmm7,xmm13       
    divpd          xmm7,xmm13       
    divsd          xmm7,xmm13       
    maxpd          xmm7,xmm13       
    maxsd          xmm7,xmm13       
    punpcklbw      xmm7,xmm13         
    punpcklwd      xmm7,xmm13         
    punpckldq      xmm7,xmm13         
    packsswb       xmm7,xmm13         
    pcmpgtb        xmm7,xmm13         
    pcmpgtw        xmm7,xmm13         
    pcmpgtd        xmm7,xmm13         
    packuswb       xmm7,xmm13         
    punpckhbw      xmm7,xmm13         
    punpckhwd      xmm7,xmm13         
    punpckhdq      xmm7,xmm13         
    packssdw       xmm7,xmm13         
    punpcklqdq     xmm7,xmm13         
    punpckhqdq     xmm7,xmm13                
    movd           xmm7,edx
    movq           xmm7,rdx        
    movdqa         xmm7,xmm13         
    movdqu         xmm7,xmm13         
    pshufd         xmm7,xmm13,10      
    pshufhw        xmm7,xmm13,10      
    pshuflw        xmm7,xmm13,10      
    psrlw          xmm7,10         
    psraw          xmm7,10         
    psllw          xmm7,10         
    psrld          xmm7,10         
    psrad          xmm7,10         
    pslld          xmm7,10         
    psrlq          xmm7,10         
    psrldq         xmm7,10         
    psllq          xmm7,10         
    pslldq         xmm7,10         
    pcmpeqb        xmm7,xmm13         
    pcmpeqw        xmm7,xmm13         
    pcmpeqd        xmm7,xmm13         
    movd           edx,xmm7        
    movq           rdx,xmm7        
    movq           xmm7,xmm13        
    movdqa         xmm13,xmm7         
    movdqu         xmm13,xmm7                  
    cmppd          xmm7,xmm13,10    
    cmpsd          xmm7,xmm13,10    
    movnti         [rbx],edx
    pinsrw         xmm7,edx,10     
    pinsrw         xmm7,[rbx],10     
    pextrw         edx,xmm7,10     
    pextrw         rdx,xmm7,10     
    shufpd         xmm7,xmm13,10    
    psrlw          xmm7,xmm13         
    psrld          xmm7,xmm13         
    psrlq          xmm7,xmm13             
    paddq          xmm7,xmm13         
    pmullw         xmm7,xmm13         
    movq           xmm13,xmm7         
    movq2dq        xmm7,mm0
    pmovmskb       edx,xmm7
    psubusb        xmm7,xmm13         
    psubusw        xmm7,xmm13         
    pminub         xmm7,xmm13         
    pand           xmm7,xmm13         
    paddusb        xmm7,xmm13         
    paddusw        xmm7,xmm13         
    pmaxub         xmm7,xmm13         
    pandn          xmm7,xmm13         
    pavgb          xmm7,xmm13         
    psraw          xmm7,xmm13         
    psrad          xmm7,xmm13         
    pavgw          xmm7,xmm13         
    pmulhuw        xmm7,xmm13         
    pmulhw         xmm7,xmm13         
    cvttpd2dq      xmm7,xmm13        
    cvtdq2pd       xmm7,xmm13        
    cvtpd2dq       xmm7,xmm13        
    movntdq        [rbx],xmm7         
    psubsb         xmm7,xmm13         
    psubsw         xmm7,xmm13         
    pminsw         xmm7,xmm13         
    por            xmm7,xmm13         
    paddsb         xmm7,xmm13         
    paddsw         xmm7,xmm13         
    pmaxsw         xmm7,xmm13         
    pxor           xmm7,xmm13         
    psllw          xmm7,xmm13         
    pslld          xmm7,xmm13         
    psllq          xmm7,xmm13         
    pmuludq        xmm7,xmm13         
    pmaddwd        xmm7,xmm13         
    psadbw         xmm7,xmm13         
    maskmovdqu     xmm7,xmm7       
    psubb          xmm7,xmm13         
    psubw          xmm7,xmm13         
    psubd          xmm7,xmm13         
    psubq          xmm7,xmm13         
    paddb          xmm7,xmm13         
    paddw          xmm7,xmm13         
    paddd          xmm7,xmm13         

    movupd         xmm7,[rbx]       
    movsd          xmm7,[rbx]       
    movupd         [rbx],xmm7       
    movsd          [rbx],xmm7       
    movlpd         xmm7,[rbx]        
    movlpd         [rbx],xmm7        
    unpcklpd       xmm7,[rbx]         
    unpckhpd       xmm7,[rbx]         
    movhpd         xmm7,[rbx]         
    movhpd         [rbx],xmm7         
    movapd         xmm7,[rbx]       
    movapd         [rbx],xmm7       
    cvtsi2sd       xmm7,edx        
    cvtsi2sd       xmm7,rdx
    movntpd        [rbx],xmm7       
    cvttsd2si      edx,[rbx]        
    cvttsd2si      rdx,[rbx]        
    cvtsd2si       edx,[rbx]        
    cvtsd2si       rdx,[rbx]        
    ucomisd        xmm7,[rbx]       
    comisd         xmm7,[rbx]       
    movmskpd       eax,xmm7
    sqrtpd         xmm7,[rbx]       
    sqrtsd         xmm7,[rbx]       
    andpd          xmm7,[rbx]       
    andnpd         xmm7,[rbx]       
    orpd           xmm7,[rbx]       
    xorpd          xmm7,[rbx]       
    addpd          xmm7,[rbx]       
    addsd          xmm7,[rbx]       
    mulpd          xmm7,[rbx]       
    mulsd          xmm7,[rbx]       
    cvtps2pd       xmm7,[rbx]        
    cvtpd2ps       xmm7,[rbx]       
    cvtss2sd       xmm7,[rbx]       
    cvtsd2ss       xmm7,[rbx]       
    cvtdq2ps       xmm7,[rbx]       
    cvtps2dq       xmm7,[rbx]       
    cvttps2dq      xmm7,[rbx]       
    subpd          xmm7,[rbx]       
    subsd          xmm7,[rbx]       
    minpd          xmm7,[rbx]       
    minsd          xmm7,[rbx]       
    divpd          xmm7,[rbx]       
    divsd          xmm7,[rbx]       
    maxpd          xmm7,[rbx]       
    maxsd          xmm7,[rbx]       
    punpcklbw      xmm7,[rbx]         
    punpcklwd      xmm7,[rbx]         
    punpckldq      xmm7,[rbx]         
    packsswb       xmm7,[rbx]         
    pcmpgtb        xmm7,[rbx]         
    pcmpgtw        xmm7,[rbx]         
    pcmpgtd        xmm7,[rbx]         
    packuswb       xmm7,[rbx]         
    punpckhbw      xmm7,[rbx]         
    punpckhwd      xmm7,[rbx]         
    punpckhdq      xmm7,[rbx]         
    packssdw       xmm7,[rbx]         
    punpcklqdq     xmm7,[rbx]         
    punpckhqdq     xmm7,[rbx]                
    movd           xmm7,edx
    movq           xmm7,rdx        
    movdqa         xmm7,[rbx]         
    movdqu         xmm7,[rbx]         
    pshufd         xmm7,[rbx],10      
    pshufhw        xmm7,[rbx],10      
    pshuflw        xmm7,[rbx],10      
    psrlw          xmm7,10         
    psraw          xmm7,10         
    psllw          xmm7,10         
    psrld          xmm7,10         
    psrad          xmm7,10         
    pslld          xmm7,10         
    psrlq          xmm7,10         
    psrldq         xmm7,10         
    psllq          xmm7,10         
    pslldq         xmm7,10         
    pcmpeqb        xmm7,[rbx]         
    pcmpeqw        xmm7,[rbx]         
    pcmpeqd        xmm7,[rbx]         
    movd           edx,xmm7        
    movq           rdx,xmm7        
    movq           xmm7,[rbx]        
    movdqa         [rbx],xmm7         
    movdqu         [rbx],xmm7                  
    cmppd          xmm7,[rbx],10    
    cmpsd          xmm7,[rbx],10    
    movnti         [rbx],edx
    pinsrw         xmm7,edx,10     
    pinsrw         xmm7,[rbx],10     
    pextrw         edx,xmm7,10     
    pextrw         rdx,xmm7,10     
    shufpd         xmm7,[rbx],10    
    psrlw          xmm7,[rbx]         
    psrld          xmm7,[rbx]         
    psrlq          xmm7,[rbx]             
    paddq          xmm7,[rbx]         
    pmullw         xmm7,[rbx]         
    movq           [rbx],xmm7         
    movq2dq        xmm7,mm0
    pmovmskb       edx,xmm7
    psubusb        xmm7,[rbx]         
    psubusw        xmm7,[rbx]         
    pminub         xmm7,[rbx]         
    pand           xmm7,[rbx]         
    paddusb        xmm7,[rbx]         
    paddusw        xmm7,[rbx]         
    pmaxub         xmm7,[rbx]         
    pandn          xmm7,[rbx]         
    pavgb          xmm7,[rbx]         
    psraw          xmm7,[rbx]         
    psrad          xmm7,[rbx]         
    pavgw          xmm7,[rbx]         
    pmulhuw        xmm7,[rbx]         
    pmulhw         xmm7,[rbx]         
    cvttpd2dq      xmm7,[rbx]        
    cvtdq2pd       xmm7,[rbx]        
    cvtpd2dq       xmm7,[rbx]        
    movntdq        [rbx],xmm7         
    psubsb         xmm7,[rbx]         
    psubsw         xmm7,[rbx]         
    pminsw         xmm7,[rbx]         
    por            xmm7,[rbx]         
    paddsb         xmm7,[rbx]         
    paddsw         xmm7,[rbx]         
    pmaxsw         xmm7,[rbx]         
    pxor           xmm7,[rbx]         
    psllw          xmm7,[rbx]         
    pslld          xmm7,[rbx]         
    psllq          xmm7,[rbx]         
    pmuludq        xmm7,[rbx]         
    pmaddwd        xmm7,[rbx]         
    psadbw         xmm7,[rbx]         
    maskmovdqu     xmm7,xmm7       
    psubb          xmm7,[rbx]         
    psubw          xmm7,[rbx]         
    psubd          xmm7,[rbx]         
    psubq          xmm7,[rbx]         
    paddb          xmm7,[rbx]         
    paddw          xmm7,[rbx]         
    paddd          xmm7,[rbx] 