    bits 64
       
    movsldup       xmm7,xmm13    
    movddup        xmm7,xmm13   
    movshdup       xmm7,xmm13    
    haddpd         xmm7,xmm13  
    haddps         xmm7,xmm13  
    hsubpd         xmm7,xmm13  
    hsubps         xmm7,xmm13  
    addsubpd       xmm7,xmm13  
    addsubps       xmm7,xmm13  
    lddqu          xmm7,[rbx]    
    pshufb         xmm7,xmm13    
    phaddw         xmm7,xmm13    
    phaddd         xmm7,xmm13    
    phaddsw        xmm7,xmm13    
    pmaddubsw      xmm7,xmm13    
    phsubw         xmm7,xmm13    
    phsubd         xmm7,xmm13    
    phsubsw        xmm7,xmm13    
    psignb         xmm7,xmm13    
    psignw         xmm7,xmm13    
    psignd         xmm7,xmm13    
    pmulhrsw       xmm7,xmm13    
    pabsb          xmm7,xmm13    
    pabsw          xmm7,xmm13    
    pabsd          xmm7,xmm13    
    palignr        xmm7,xmm13,10
    
    movsldup       xmm7,[rbx]    
    movddup        xmm7,[rbx]   
    movshdup       xmm7,[rbx]    
    haddpd         xmm7,[rbx]  
    haddps         xmm7,[rbx]  
    hsubpd         xmm7,[rbx]  
    hsubps         xmm7,[rbx]  
    addsubpd       xmm7,[rbx]  
    addsubps       xmm7,[rbx]  
    lddqu          xmm7,[rbx]    
    pshufb         xmm7,[rbx]    
    phaddw         xmm7,[rbx]    
    phaddd         xmm7,[rbx]    
    phaddsw        xmm7,[rbx]    
    pmaddubsw      xmm7,[rbx]    
    phsubw         xmm7,[rbx]    
    phsubd         xmm7,[rbx]    
    phsubsw        xmm7,[rbx]    
    psignb         xmm7,[rbx]    
    psignw         xmm7,[rbx]    
    psignd         xmm7,[rbx]    
    pmulhrsw       xmm7,[rbx]    
    pabsb          xmm7,[rbx]    
    pabsw          xmm7,[rbx]    
    pabsd          xmm7,[rbx]    
    palignr        xmm7,[rbx],10
