    bits 64
    
    movntss        [rbx],xmm7       
    movntsd        [rbx],xmm7       
    insertq        xmm7,xmm7,10,10 
    extrq          xmm7,10,10      
    extrq          xmm7,xmm7        
    insertq        xmm7,xmm7       
    pblendvb       xmm7,xmm13            
    blendvps       xmm7,xmm13            
    blendvpd       xmm7,xmm13            
    ptest          xmm7,xmm13            
    pmovsxbw       xmm7,xmm13             
    pmovsxbd       xmm7,xmm13             
    pmovsxbq       xmm7,xmm13             
    pmovsxwd       xmm7,xmm13             
    pmovsxwq       xmm7,xmm13             
    pmovsxdq       xmm7,xmm13             
    pmuldq         xmm7,xmm13              
    pcmpeqq        xmm7,xmm13              
    movntdqa       xmm7,[rbx]              
    packusdw       xmm7,xmm13              
    pmovzxbw       xmm7,xmm13             
    pmovzxbd       xmm7,xmm13             
    pmovzxbq       xmm7,xmm13             
    pmovzxwd       xmm7,xmm13             
    pmovzxwq       xmm7,xmm13             
    pmovzxdq       xmm7,xmm13             
    pcmpgtq        xmm7,xmm13              
    pminsb         xmm7,xmm13              
    pminsd         xmm7,xmm13              
    pminuw         xmm7,xmm13              
    pminud         xmm7,xmm13              
    pmaxsb         xmm7,xmm13              
    pmaxsd         xmm7,xmm13              
    pmaxuw         xmm7,xmm13              
    pmaxud         xmm7,xmm13              
    pmulld         xmm7,xmm13              
    phminposuw     xmm7,xmm13            
    roundps        xmm7,xmm13,10           
    roundpd        xmm7,xmm13,10           
    roundss        xmm7,xmm13,10         
    roundsd        xmm7,xmm13,10         
    blendps        xmm7,xmm13,10           
    blendpd        xmm7,xmm13,10           
    pblendw        xmm7,xmm13,10           
    pextrb         [rbx],xmm7,10          
    pextrb         edx,xmm7,10          
    pextrw         [rbx],xmm7,10          
    pextrw         edx,xmm7,10                
    pextrd         edx,xmm7,10          
    pextrq         rdx,xmm7,10          
    extractps      rdx,xmm7,10          
    pinsrb         xmm7,[rbx],10          
    pinsrb         xmm7,edx,10          
    insertps       xmm7,[rbx],10          
    insertps       xmm7,xmm7,10         
    pinsrd         xmm7,edx,10          
    pinsrq         xmm7,rdx,10          
    dpps           xmm7,xmm13,10           
    dppd           xmm7,xmm13,10         
    mpsadbw        xmm7,xmm13,10         
    pcmpestrm      xmm7,xmm13,10         
    pcmpestri      xmm7,xmm13,10         
    pcmpistrm      xmm7,xmm13,10         
    pcmpistri      xmm7,xmm13,10         

    movntss        [rbx],xmm7       
    movntsd        [rbx],xmm7       
    insertq        xmm7,xmm7,10,10 
    extrq          xmm7,10,10      
    extrq          xmm7,xmm7        
    insertq        xmm7,xmm7       
    pblendvb       xmm7,[rbx]            
    blendvps       xmm7,[rbx]            
    blendvpd       xmm7,[rbx]            
    ptest          xmm7,[rbx]            
    pmovsxbw       xmm7,[rbx]             
    pmovsxbd       xmm7,[rbx]             
    pmovsxbq       xmm7,[rbx]             
    pmovsxwd       xmm7,[rbx]             
    pmovsxwq       xmm7,[rbx]             
    pmovsxdq       xmm7,[rbx]             
    pmuldq         xmm7,[rbx]              
    pcmpeqq        xmm7,[rbx]              
    movntdqa       xmm7,[rbx]              
    packusdw       xmm7,[rbx]              
    pmovzxbw       xmm7,[rbx]             
    pmovzxbd       xmm7,[rbx]             
    pmovzxbq       xmm7,[rbx]             
    pmovzxwd       xmm7,[rbx]             
    pmovzxwq       xmm7,[rbx]             
    pmovzxdq       xmm7,[rbx]             
    pcmpgtq        xmm7,[rbx]              
    pminsb         xmm7,[rbx]              
    pminsd         xmm7,[rbx]              
    pminuw         xmm7,[rbx]              
    pminud         xmm7,[rbx]              
    pmaxsb         xmm7,[rbx]              
    pmaxsd         xmm7,[rbx]              
    pmaxuw         xmm7,[rbx]              
    pmaxud         xmm7,[rbx]              
    pmulld         xmm7,[rbx]              
    phminposuw     xmm7,[rbx]            
    roundps        xmm7,[rbx],10           
    roundpd        xmm7,[rbx],10           
    roundss        xmm7,[rbx],10         
    roundsd        xmm7,[rbx],10         
    blendps        xmm7,[rbx],10           
    blendpd        xmm7,[rbx],10           
    pblendw        xmm7,[rbx],10           
    pextrb         [rbx],xmm7,10          
    pextrb         edx,xmm7,10          
    pextrw         [rbx],xmm7,10          
    pextrw         edx,xmm7,10                
    pextrd         edx,xmm7,10          
    pextrq         rdx,xmm7,10          
    extractps      rdx,xmm7,10          
    pinsrb         xmm7,[rbx],10          
    pinsrb         xmm7,edx,10          
    insertps       xmm7,[rbx],10          
    insertps       xmm7,xmm7,10         
    pinsrd         xmm7,edx,10          
    pinsrq         xmm7,rdx,10          
    dpps           xmm7,[rbx],10           
    dppd           xmm7,[rbx],10         
    mpsadbw        xmm7,[rbx],10         
    pcmpestrm      xmm7,[rbx],10         
    pcmpestri      xmm7,[rbx],10         
    pcmpistrm      xmm7,[rbx],10         
    pcmpistri      xmm7,[rbx],10         
