    bits 64
    
    vfmaddsubps         xmm7,xmm15,xmm13,xmm8         
    vfmaddsubps         xmm7,xmm15,xmm8,xmm13         
    vfmaddsubpd         xmm7,xmm15,xmm13,xmm8         
    vfmaddsubpd         xmm7,xmm15,xmm8,xmm13         
    vfmsubaddps         xmm7,xmm15,xmm13,xmm8         
    vfmsubaddps         xmm7,xmm15,xmm8,xmm13         
    vfmsubaddpd         xmm7,xmm15,xmm13,xmm8         
    vfmsubaddpd         xmm7,xmm15,xmm8,xmm13         
    vfmaddps            xmm7,xmm15,xmm13,xmm8         
    vfmaddps            xmm7,xmm15,xmm8,xmm13         
    vfmaddpd            xmm7,xmm15,xmm13,xmm8         
    vfmaddpd            xmm7,xmm15,xmm8,xmm13         
    vfmaddss            xmm7,xmm15,xmm13,xmm8     
    vfmaddss            xmm7,xmm15,xmm8,xmm13     
    vfmaddsd            xmm7,xmm15,xmm13,xmm8     
    vfmaddsd            xmm7,xmm15,xmm8,xmm13     
    vfmsubps            xmm7,xmm15,xmm13,xmm8         
    vfmsubps            xmm7,xmm15,xmm8,xmm13         
    vfmsubpd            xmm7,xmm15,xmm13,xmm8         
    vfmsubpd            xmm7,xmm15,xmm8,xmm13         
    vfmsubss            xmm7,xmm15,xmm13,xmm8     
    vfmsubss            xmm7,xmm15,xmm8,xmm13     
    vfmsubsd            xmm7,xmm15,xmm13,xmm8     
    vfmsubsd            xmm7,xmm15,xmm8,xmm13     
    vfnmaddps           xmm7,xmm15,xmm13,xmm8         
    vfnmaddps           xmm7,xmm15,xmm8,xmm13         
    vfnmaddpd           xmm7,xmm15,xmm13,xmm8         
    vfnmaddpd           xmm7,xmm15,xmm8,xmm13         
    vfnmaddss           xmm7,xmm15,xmm13,xmm8     
    vfnmaddss           xmm7,xmm15,xmm8,xmm13     
    vfnmaddsd           xmm7,xmm15,xmm13,xmm8     
    vfnmaddsd           xmm7,xmm15,xmm8,xmm13     
    vfnmsubps           xmm7,xmm15,xmm13,xmm8         
    vfnmsubps           xmm7,xmm15,xmm8,xmm13         
    vfnmsubpd           xmm7,xmm15,xmm13,xmm8         
    vfnmsubpd           xmm7,xmm15,xmm8,xmm13         
    vfnmsubss           xmm7,xmm15,xmm13,xmm8     
    vfnmsubss           xmm7,xmm15,xmm8,xmm13     
    vfnmsubsd           xmm7,xmm15,xmm13,xmm8     
    vfnmsubsd           xmm7,xmm15,xmm8,xmm13  

    vfmaddsubps         xmm7,xmm15,[rbx],xmm8         
    vfmaddsubps         xmm7,xmm15,xmm8,[rbx]         
    vfmaddsubpd         xmm7,xmm15,[rbx],xmm8         
    vfmaddsubpd         xmm7,xmm15,xmm8,[rbx]         
    vfmsubaddps         xmm7,xmm15,[rbx],xmm8         
    vfmsubaddps         xmm7,xmm15,xmm8,[rbx]         
    vfmsubaddpd         xmm7,xmm15,[rbx],xmm8         
    vfmsubaddpd         xmm7,xmm15,xmm8,[rbx]         
    vfmaddps            xmm7,xmm15,[rbx],xmm8         
    vfmaddps            xmm7,xmm15,xmm8,[rbx]         
    vfmaddpd            xmm7,xmm15,[rbx],xmm8         
    vfmaddpd            xmm7,xmm15,xmm8,[rbx]         
    vfmaddss            xmm7,xmm15,[rbx],xmm8     
    vfmaddss            xmm7,xmm15,xmm8,[rbx]     
    vfmaddsd            xmm7,xmm15,[rbx],xmm8     
    vfmaddsd            xmm7,xmm15,xmm8,[rbx]     
    vfmsubps            xmm7,xmm15,[rbx],xmm8         
    vfmsubps            xmm7,xmm15,xmm8,[rbx]         
    vfmsubpd            xmm7,xmm15,[rbx],xmm8         
    vfmsubpd            xmm7,xmm15,xmm8,[rbx]         
    vfmsubss            xmm7,xmm15,[rbx],xmm8     
    vfmsubss            xmm7,xmm15,xmm8,[rbx]     
    vfmsubsd            xmm7,xmm15,[rbx],xmm8     
    vfmsubsd            xmm7,xmm15,xmm8,[rbx]     
    vfnmaddps           xmm7,xmm15,[rbx],xmm8         
    vfnmaddps           xmm7,xmm15,xmm8,[rbx]         
    vfnmaddpd           xmm7,xmm15,[rbx],xmm8         
    vfnmaddpd           xmm7,xmm15,xmm8,[rbx]         
    vfnmaddss           xmm7,xmm15,[rbx],xmm8     
    vfnmaddss           xmm7,xmm15,xmm8,[rbx]     
    vfnmaddsd           xmm7,xmm15,[rbx],xmm8     
    vfnmaddsd           xmm7,xmm15,xmm8,[rbx]     
    vfnmsubps           xmm7,xmm15,[rbx],xmm8         
    vfnmsubps           xmm7,xmm15,xmm8,[rbx]         
    vfnmsubpd           xmm7,xmm15,[rbx],xmm8         
    vfnmsubpd           xmm7,xmm15,xmm8,[rbx]         
    vfnmsubss           xmm7,xmm15,[rbx],xmm8     
    vfnmsubss           xmm7,xmm15,xmm8,[rbx]     
    vfnmsubsd           xmm7,xmm15,[rbx],xmm8     
    vfnmsubsd           xmm7,xmm15,xmm8,[rbx]      

    vfmaddsubps         ymm7,ymm15,ymm13,ymm8         
    vfmaddsubps         ymm7,ymm15,ymm8,ymm13         
    vfmaddsubpd         ymm7,ymm15,ymm13,ymm8         
    vfmaddsubpd         ymm7,ymm15,ymm8,ymm13         
    vfmsubaddps         ymm7,ymm15,ymm13,ymm8         
    vfmsubaddps         ymm7,ymm15,ymm8,ymm13         
    vfmsubaddpd         ymm7,ymm15,ymm13,ymm8         
    vfmsubaddpd         ymm7,ymm15,ymm8,ymm13         
    vfmaddps            ymm7,ymm15,ymm13,ymm8         
    vfmaddps            ymm7,ymm15,ymm8,ymm13         
    vfmaddpd            ymm7,ymm15,ymm13,ymm8         
    vfmaddpd            ymm7,ymm15,ymm8,ymm13         
    vfmsubps            ymm7,ymm15,ymm13,ymm8         
    vfmsubps            ymm7,ymm15,ymm8,ymm13         
    vfmsubpd            ymm7,ymm15,ymm13,ymm8         
    vfmsubpd            ymm7,ymm15,ymm8,ymm13         
    vfnmaddps           ymm7,ymm15,ymm13,ymm8         
    vfnmaddps           ymm7,ymm15,ymm8,ymm13         
    vfnmaddpd           ymm7,ymm15,ymm13,ymm8         
    vfnmaddpd           ymm7,ymm15,ymm8,ymm13         
    vfnmsubps           ymm7,ymm15,ymm13,ymm8         
    vfnmsubps           ymm7,ymm15,ymm8,ymm13         
    vfnmsubpd           ymm7,ymm15,ymm13,ymm8         
    vfnmsubpd           ymm7,ymm15,ymm8,ymm13         

    vfmaddsubps         ymm7,ymm15,[rbx],ymm8         
    vfmaddsubps         ymm7,ymm15,ymm8,[rbx]         
    vfmaddsubpd         ymm7,ymm15,[rbx],ymm8         
    vfmaddsubpd         ymm7,ymm15,ymm8,[rbx]         
    vfmsubaddps         ymm7,ymm15,[rbx],ymm8         
    vfmsubaddps         ymm7,ymm15,ymm8,[rbx]         
    vfmsubaddpd         ymm7,ymm15,[rbx],ymm8         
    vfmsubaddpd         ymm7,ymm15,ymm8,[rbx]         
    vfmaddps            ymm7,ymm15,[rbx],ymm8         
    vfmaddps            ymm7,ymm15,ymm8,[rbx]         
    vfmaddpd            ymm7,ymm15,[rbx],ymm8         
    vfmaddpd            ymm7,ymm15,ymm8,[rbx]         
    vfmsubps            ymm7,ymm15,[rbx],ymm8         
    vfmsubps            ymm7,ymm15,ymm8,[rbx]         
    vfmsubpd            ymm7,ymm15,[rbx],ymm8         
    vfmsubpd            ymm7,ymm15,ymm8,[rbx]         
    vfnmaddps           ymm7,ymm15,[rbx],ymm8         
    vfnmaddps           ymm7,ymm15,ymm8,[rbx]         
    vfnmaddpd           ymm7,ymm15,[rbx],ymm8         
    vfnmaddpd           ymm7,ymm15,ymm8,[rbx]         
    vfnmsubps           ymm7,ymm15,[rbx],ymm8         
    vfnmsubps           ymm7,ymm15,ymm8,[rbx]         
    vfnmsubpd           ymm7,ymm15,[rbx],ymm8         
    vfnmsubpd           ymm7,ymm15,ymm8,[rbx]         
